export type GlossaryTerm = {
  slug: string;
  title: string;
  summary: string;
  definition: string;
  examples: string[];
  faq: { question: string; answer: string }[];
  related: string[];
};

export const glossaryTerms: GlossaryTerm[] = [
  { slug: 'aee', title: 'AEE (Atendimento Educacional Especializado)', summary: 'Serviço que complementa a escolarização de estudantes público-alvo da Educação Especial.', definition: 'O Atendimento Educacional Especializado é um conjunto de recursos e estratégias que apoia a participação e a aprendizagem de estudantes com deficiência, transtorno do espectro autista e altas habilidades. Ele não substitui a sala de aula regular: complementa o ensino com adaptações, tecnologias assistivas e organização de recursos.', examples: ['Rotina visual com pictogramas.', 'Atividade com fonte ampliada e alto contraste.', 'Prancha de comunicação alternativa.'], faq: [{ question: 'O AEE substitui a aula regular?', answer: 'Não. Ele complementa o ensino e apoia a participação do estudante na turma regular.' }], related: ['educacao-especial', 'material-adaptado'] },
  { slug: 'alfabetizacao', title: 'Alfabetização', summary: 'Processo de apropriação da leitura e da escrita.', definition: 'Alfabetização é o processo em que a criança compreende o funcionamento do sistema de escrita alfabética e passa a ler e escrever. Materiais de consciência fonológica, letras, sílabas, palavras e leitura compartilhada podem tornar esse percurso mais significativo.', examples: ['Jogo de associação entre letras e sons.', 'Fichas de leitura de palavras simples.', 'Bingo de sílabas.'], faq: [{ question: 'Alfabetização e letramento são a mesma coisa?', answer: 'São complementares: alfabetizar envolve compreender a escrita; letrar envolve usá-la em situações reais de comunicação.' }], related: ['letramento', 'sequencia-didatica', 'bncc'] },
  { slug: 'atividade-pedagogica', title: 'Atividade pedagógica', summary: 'Proposta planejada para favorecer uma aprendizagem específica.', definition: 'Atividade pedagógica é uma proposta organizada com objetivo, público, recursos e forma de acompanhamento. Ela pode envolver leitura, jogos, experimentos, registros ou produção coletiva, sempre conectada ao que a turma precisa aprender.', examples: ['Caça-palavras sobre animais.', 'Experimento simples de Ciências.', 'Roda de leitura com registro ilustrado.'], faq: [{ question: 'Toda atividade precisa de objetivo?', answer: 'Sim. O objetivo ajuda a escolher o recurso adequado e a observar se a aprendizagem aconteceu.' }], related: ['plano-de-aula', 'sequencia-didatica', 'avaliacao-diagnostica'] },
  { slug: 'avaliacao-diagnostica', title: 'Avaliação diagnóstica', summary: 'Levantamento do que a turma já sabe antes ou durante o ensino.', definition: 'Avaliação diagnóstica é uma estratégia para identificar conhecimentos prévios, dificuldades e necessidades da turma. Ela orienta o planejamento e não precisa ter caráter classificatório.', examples: ['Sondagem de escrita.', 'Problemas matemáticos de entrada.', 'Conversa guiada sobre um tema novo.'], faq: [{ question: 'A avaliação diagnóstica vale nota?', answer: 'Ela pode compor o acompanhamento, mas sua principal função é orientar as próximas decisões de ensino.' }], related: ['plano-de-aula', 'atividade-pedagogica', 'bncc'] },
  { slug: 'bncc', title: 'BNCC (Base Nacional Comum Curricular)', summary: 'Documento que define aprendizagens essenciais da Educação Básica.', definition: 'A Base Nacional Comum Curricular orienta as aprendizagens essenciais que estudantes brasileiros devem desenvolver ao longo da Educação Básica. Ela organiza competências e habilidades por etapa, ano e componente curricular, ajudando o professor a planejar e selecionar materiais.', examples: ['Plano de aula ligado a uma habilidade de Matemática.', 'Sequência de leitura com objetivo de Língua Portuguesa.', 'Projeto interdisciplinar com competências gerais.'], faq: [{ question: 'Todo material precisa indicar BNCC?', answer: 'Nem todo recurso precisa exibir códigos, mas indicar objetivos e habilidades torna a escolha do material mais clara.' }], related: ['plano-de-aula', 'sequencia-didatica', 'ensino-fundamental'] },
  { slug: 'educacao-especial', title: 'Educação Especial', summary: 'Modalidade transversal que promove acesso, participação e aprendizagem com equidade.', definition: 'Educação Especial reúne serviços, recursos e estratégias para garantir participação e aprendizagem de estudantes público-alvo da educação especial. Materiais acessíveis, rotina visual, comunicação alternativa e adaptações são exemplos de apoios possíveis.', examples: ['Cartaz com pictogramas.', 'Jogo com contraste ampliado.', 'Rotina da sala em imagens.'], faq: [{ question: 'Material adaptado é útil para toda a turma?', answer: 'Muitas adaptações tornam os conteúdos mais claros para todos, respeitando diferentes formas de aprender.' }], related: ['aee', 'material-adaptado', 'atividade-pedagogica'] },
  { slug: 'ensino-fundamental', title: 'Ensino Fundamental', summary: 'Etapa obrigatória da Educação Básica composta por nove anos.', definition: 'O Ensino Fundamental atende estudantes dos anos iniciais e finais, organizando progressivamente aprendizagens de diferentes áreas. Materiais podem ser filtrados por ano, disciplina, habilidade e tema para apoiar o planejamento.', examples: ['Apostila de leitura para o 3º ano.', 'Jogo de frações para o 5º ano.', 'Projeto de Ciências para o 6º ano.'], faq: [{ question: 'Quais anos formam os anos iniciais?', answer: 'Do 1º ao 5º ano. Os anos finais vão do 6º ao 9º ano.' }], related: ['bncc', 'plano-de-aula', 'material-didatico-digital'] },
  { slug: 'letramento', title: 'Letramento', summary: 'Uso social da leitura e da escrita em situações reais.', definition: 'Letramento é a participação em práticas sociais de leitura e escrita. Enquanto a alfabetização focaliza o sistema de escrita, o letramento aproxima a criança de bilhetes, listas, histórias, receitas, placas e outros textos reais.', examples: ['Escrever uma lista de compras.', 'Ler uma receita em grupo.', 'Produzir convite para evento da escola.'], faq: [{ question: 'É possível alfabetizar letrando?', answer: 'Sim. Trabalhar textos reais junto a atividades de escrita favorece os dois processos.' }], related: ['alfabetizacao', 'sequencia-didatica', 'atividade-pedagogica'] },
  { slug: 'material-adaptado', title: 'Material adaptado', summary: 'Recurso ajustado para reduzir barreiras de acesso e participação.', definition: 'Material adaptado é qualquer recurso pedagógico que recebe ajustes de linguagem, visual, tamanho, suporte ou interação para atender necessidades específicas de aprendizagem e acessibilidade.', examples: ['Texto com fonte ampliada.', 'Jogo com comandos visuais.', 'Atividade com menos itens por página.'], faq: [{ question: 'Adaptar é simplificar o conteúdo?', answer: 'Nem sempre. Adaptar significa remover barreiras e oferecer caminhos para acessar o objetivo de aprendizagem.' }], related: ['educacao-especial', 'aee', 'atividade-pedagogica'] },
  { slug: 'material-didatico-digital', title: 'Material didático digital', summary: 'Recurso pedagógico distribuído em formato eletrônico.', definition: 'Material didático digital é um recurso distribuído em formatos como PDF, apresentação, imagem, planilha, áudio ou vídeo. Pode ser impresso, projetado ou utilizado em celular, tablet e computador conforme a proposta pedagógica.', examples: ['Apostila em PDF.', 'Cartelas para imprimir.', 'Apresentação de aula.'], faq: [{ question: 'Posso imprimir um material digital?', answer: 'Sim, quando o formato e a licença do produto permitirem a impressão para uso pedagógico.' }], related: ['atividade-pedagogica', 'professor-criador', 'plano-de-aula'] },
  { slug: 'plano-de-aula', title: 'Plano de aula', summary: 'Organização intencional de uma experiência de ensino.', definition: 'Plano de aula é o registro do caminho pensado para uma aula: objetivos, habilidades, etapas, recursos, tempo e formas de acompanhamento. Ele traz clareza ao planejamento e pode ser ajustado conforme a resposta da turma.', examples: ['Aula de leitura com antecipação, leitura e conversa.', 'Aula de Matemática com situação-problema.', 'Projeto de Ciências com experimento e registro.'], faq: [{ question: 'Plano de aula precisa ser longo?', answer: 'Não. Ele precisa ser claro o suficiente para orientar a intenção pedagógica e as próximas decisões.' }], related: ['bncc', 'sequencia-didatica', 'avaliacao-diagnostica'] },
  { slug: 'professor-criador', title: 'Professor criador', summary: 'Educador que transforma sua experiência em materiais pedagógicos autorais.', definition: 'Professor criador é o educador que organiza atividades, planos, jogos e recursos próprios para compartilhar ou comercializar. Na Educalizando, ele pode publicar materiais digitais, montar uma loja e acompanhar suas vendas.', examples: ['Professora que vende fichas de leitura.', 'Pedagogo que publica planos de aula.', 'Criador que produz recursos adaptados.'], faq: [{ question: 'Preciso ser designer para criar materiais?', answer: 'Não. O mais importante é a clareza pedagógica; as ferramentas da plataforma ajudam a preparar os arquivos e as capas.' }], related: ['material-didatico-digital', 'plano-de-aula', 'atividade-pedagogica'] },
  { slug: 'sequencia-didatica', title: 'Sequência didática', summary: 'Conjunto articulado de aulas para desenvolver uma aprendizagem.', definition: 'Sequência didática é uma organização de atividades conectadas entre si, planejadas para levar a turma de um ponto de partida a uma aprendizagem definida. Ela costuma incluir apresentação do tema, exploração, sistematização e acompanhamento.', examples: ['Sequência de leitura de contos.', 'Projeto sobre meio ambiente.', 'Percurso de escrita de cartas.'], faq: [{ question: 'Quantas aulas uma sequência didática tem?', answer: 'Não há número fixo: ela dura o tempo necessário para desenvolver o objetivo previsto.' }], related: ['plano-de-aula', 'bncc', 'alfabetizacao'] },
];

export const getGlossaryTerm = (slug: string) => glossaryTerms.find((term) => term.slug === slug);
