import type { IntentLanding } from '@/components/seo/IntentLandingPage';
import { socialMetadata } from '@/lib/seo';
import type { Metadata } from 'next';

export const seoLandings: Record<string, IntentLanding> = {
  'materiais-didaticos': { slug: 'materiais-didaticos', eyebrow: 'Recursos para educadores', title: 'Materiais didáticos digitais para ensinar com mais praticidade', description: 'Encontre atividades, apostilas, jogos pedagógicos e recursos digitais criados por educadores para apoiar suas aulas e reduzir o tempo de planejamento.', query: 'material', benefits: ['Acesso digital após a compra', 'Recursos feitos por educadores', 'Opções para diferentes etapas de ensino'], tips: ['Confira a faixa etária, o tema e o formato antes de comprar.', 'Escolha materiais que indiquem objetivos pedagógicos claros.', 'Salve seus favoritos para organizar o planejamento da semana.'], faq: [{ question: 'Os materiais são digitais?', answer: 'Sim. Cada produto informa seu formato e fica disponível conforme as condições de compra.' }, { question: 'Posso usar no celular?', answer: 'Os materiais digitais podem ser acessados pela área do cliente em dispositivos compatíveis.' }] },
  'atividades-alfabetizacao': { slug: 'atividades-alfabetizacao', eyebrow: 'Alfabetização e letramento', title: 'Atividades de alfabetização para imprimir e usar em sala', description: 'Explore atividades de alfabetização, leitura, escrita, letras e sílabas para tornar o aprendizado mais significativo e divertido.', query: 'alfabetização', benefits: ['Atividades prontas para imprimir', 'Recursos lúdicos de leitura e escrita', 'Materiais para diferentes níveis'], tips: ['Considere a hipótese de escrita de cada criança.', 'Alterne jogos, leitura compartilhada e registros escritos.', 'Use o material como parte de uma sequência, não como tarefa isolada.'], faq: [{ question: 'Há materiais para Educação Infantil?', answer: 'Sim. Use os filtros do catálogo para combinar alfabetização com a etapa de ensino.' }, { question: 'Posso imprimir as atividades?', answer: 'Consulte o formato e a licença de cada produto antes de imprimir.' }] },
  'educacao-infantil': { slug: 'educacao-infantil', eyebrow: 'Aprender brincando', title: 'Materiais para Educação Infantil: brincadeiras, rotina e descobertas', description: 'Recursos pedagógicos para Educação Infantil com propostas lúdicas, visuais e adequadas às experiências das crianças.', query: 'educação infantil', benefits: ['Ideias para rotina e projetos', 'Recursos lúdicos e visuais', 'Materiais para imprimir e explorar'], tips: ['Priorize propostas que valorizem brincadeira e interação.', 'Adapte o tempo da atividade ao ritmo da turma.', 'Use imagens grandes, linguagem simples e materiais seguros.'], faq: [{ question: 'Os materiais servem para creche e pré-escola?', answer: 'Verifique a faixa etária e a descrição do produto para escolher a proposta adequada.' }, { question: 'Como encontrar temas específicos?', answer: 'Use a busca do catálogo com temas como cores, animais, rotina ou datas comemorativas.' }] },
  'planos-de-aula-bncc': { slug: 'planos-de-aula-bncc', eyebrow: 'Planejamento pedagógico', title: 'Planos de aula e recursos alinhados à BNCC', description: 'Planeje aulas com mais clareza usando recursos que ajudam a organizar objetivos, habilidades e experiências de aprendizagem.', query: 'plano de aula', benefits: ['Mais organização no planejamento', 'Objetivos pedagógicos claros', 'Recursos para diversas disciplinas'], tips: ['Comece pela habilidade e pelo objetivo de aprendizagem.', 'Escolha atividades coerentes com o tempo e os recursos disponíveis.', 'Registre observações para ajustar o próximo encontro.'], faq: [{ question: 'Todo plano de aula precisa trazer códigos BNCC?', answer: 'O importante é que a proposta esteja conectada a objetivos e habilidades adequados à turma.' }, { question: 'Posso adaptar um plano encontrado?', answer: 'Sim. Ajuste o contexto, o tempo e as necessidades da sua turma.' }] },
  'atividades-para-imprimir': { slug: 'atividades-para-imprimir', eyebrow: 'Prontas para usar', title: 'Atividades para imprimir: recursos escolares para a sala de aula', description: 'Encontre atividades escolares digitais para imprimir, adaptar e usar no planejamento de aulas com crianças.', query: 'atividade', benefits: ['Materiais digitais prontos para imprimir', 'Opções para diferentes temas e faixas etárias', 'Mais tempo para adaptar a aula à sua turma'], tips: ['Leia a descrição para confirmar o formato do arquivo.', 'Priorize atividades que indiquem objetivo e público.', 'Use a proposta como apoio e adapte ao contexto da turma.'], faq: [{ question: 'As atividades são entregues em formato digital?', answer: 'Sim. Confira o formato indicado na página de cada material antes da compra.' }, { question: 'Posso usar em casa ou na escola?', answer: 'Verifique a licença do produto e escolha o material adequado ao seu contexto de uso.' }] },
  'jogos-pedagogicos': { slug: 'jogos-pedagogicos', eyebrow: 'Aprendizagem lúdica', title: 'Jogos pedagógicos para aprender brincando', description: 'Descubra jogos pedagógicos digitais para trabalhar leitura, escrita, matemática, raciocínio e interação em diferentes momentos da aula.', query: 'jogo', benefits: ['Propostas lúdicas e objetivas', 'Recursos para imprimir e organizar', 'Aprendizagem ativa para diferentes turmas'], tips: ['Defina o objetivo de aprendizagem antes de apresentar o jogo.', 'Explique as regras com exemplos curtos.', 'Registre o que a turma aprendeu após a brincadeira.'], faq: [{ question: 'Há jogos para alfabetização?', answer: 'Use a busca do catálogo para combinar jogos com alfabetização, letras, sílabas ou leitura.' }, { question: 'Os jogos podem ser usados em pequenos grupos?', answer: 'Confira a descrição de cada material para entender a proposta e adaptar a organização da turma.' }] },
  'atividades-ensino-fundamental': { slug: 'atividades-ensino-fundamental', eyebrow: 'Anos iniciais e finais', title: 'Atividades para Ensino Fundamental por tema e disciplina', description: 'Materiais didáticos para apoiar o Ensino Fundamental com atividades, jogos, apostilas e recursos para diferentes disciplinas.', query: 'ensino fundamental', benefits: ['Recursos para organizar a rotina de aula', 'Materiais por tema, disciplina e nível', 'Atividades para complementar sequências didáticas'], tips: ['Combine a atividade com o objetivo previsto para a turma.', 'Use os filtros por nível, disciplina e formato.', 'Observe as necessidades dos alunos ao adaptar a proposta.'], faq: [{ question: 'Há materiais para diferentes anos do Ensino Fundamental?', answer: 'Sim. Use os filtros de nível de ensino e leia a descrição antes de escolher.' }, { question: 'Como buscar por disciplina?', answer: 'No catálogo, selecione a disciplina ou pesquise termos como português, matemática ou ciências.' }] },
  'recursos-pedagogicos': { slug: 'recursos-pedagogicos', eyebrow: 'Planejamento com propósito', title: 'Recursos pedagógicos digitais para professores', description: 'Explore recursos pedagógicos digitais criados por educadores para apoiar planejamento, intervenções e experiências de aprendizagem.', query: 'material', benefits: ['Catálogo de recursos criados por educadores', 'Filtros por etapa, tema e formato', 'Materiais para apoiar o planejamento semanal'], tips: ['Busque pelo objetivo da sua aula, não apenas pelo nome do conteúdo.', 'Confira a descrição, o formato e a licença antes de comprar.', 'Salve referências para construir uma sequência pedagógica coerente.'], faq: [{ question: 'O que são recursos pedagógicos digitais?', answer: 'São materiais digitais que apoiam o planejamento e o desenvolvimento de atividades de ensino.' }, { question: 'Como encontrar um recurso para um tema específico?', answer: 'Pesquise pelo tema no catálogo e combine os filtros de categoria, etapa e formato.' }] },
};

export function intentLandingMetadata(landing: IntentLanding): Metadata {
  const canonical = `/${landing.slug}`;
  return {
    title: `${landing.title} | Educalizando`,
    description: landing.description,
    alternates: { canonical },
    ...socialMetadata({ title: `${landing.title} | Educalizando`, description: landing.description, url: canonical }),
  };
}
