'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CalendarDays, GraduationCap, PackageSearch, RotateCcw, Search, Send, Sparkles, Tag } from 'lucide-react';
import type { Product, Store } from '@/lib/types';

type Message = { side: 'bot' | 'visitor'; text: string };
type Filter = 'all' | 'category' | 'level' | 'offers' | 'date';
const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR');
const related: Record<string, string[]> = { alfabetizacao: ['alfabetizacao', 'leitura', 'escrita', 'silabas'], matematica: ['matematica', 'numeros', 'contagem', 'adicao', 'tabuada'], portugues: ['portugues', 'leitura', 'escrita', 'gramatica'], meio: ['meio ambiente', 'ambiental', 'natureza'], natal: ['natal', 'dezembro'], pascoa: ['pascoa', 'coelho'] };
function similar(product: Product, raw: string) { const query = normalize(raw).trim(); if (!query) return true; const text = normalize(`${product.titulo} ${product.descricao || ''} ${product.category?.nome || ''} ${product.education_level?.nome || ''} ${(product.seasonal_tags || []).join(' ')}`); return query.split(/\s+/).filter(word => word.length > 1).flatMap(word => related[word] || [word]).some(word => text.includes(word) || text.split(/\W+/).some(candidate => candidate.startsWith(word.slice(0, Math.max(3, word.length - 2))))); }

export default function GuidedStoreChat({ store, products }: { store: Store; products: Product[] }) {
  const welcome = store.guided_chat_welcome || `Olá! 👋 Bem-vindo à ${store.nome_loja}. Escolha uma opção abaixo para encontrar o material ideal.`;
  const [messages, setMessages] = useState<Message[]>([{ side: 'bot', text: welcome }]); const [term, setTerm] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<Filter>('all'); const scrollRef = useRef<HTMLDivElement>(null);
  const categories = useMemo(() => Array.from(new Set(products.map(p => p.category?.nome).filter(Boolean))) as string[], [products]); const levels = useMemo(() => Array.from(new Set(products.map(p => p.education_level?.nome).filter(Boolean))) as string[], [products]); const dates = useMemo(() => Array.from(new Set(products.flatMap(p => p.seasonal_tags || []))).slice(0, 12), [products]);
  const matches = useMemo(() => products.filter(product => similar(product, query)).filter(product => filter !== 'offers' || Number(product.preco_original || 0) > Number(product.preco)), [filter, products, query]);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages, filter, query]);
  const bot = (text: string) => setMessages(current => [...current, { side: 'bot', text }]);
  const chooseFilter = (label: string, next: Filter) => { setMessages(current => [...current, { side: 'visitor', text: label }]); setFilter(next); setQuery(''); bot(next === 'offers' ? 'Aqui estão as ofertas desta loja.' : next === 'category' ? 'Escolha uma categoria abaixo.' : next === 'level' ? 'Escolha a série ou nível de ensino.' : 'Escolha uma data ou tema comemorativo.'); };
  const chooseValue = (value: string) => { setTerm(value); setQuery(value); setMessages(current => [...current, { side: 'visitor', text: value }]); bot(`Separei os materiais relacionados a “${value}”.`); };
  const submit = () => { const value = term.trim(); if (!value) return; setQuery(value); setMessages(current => [...current, { side: 'visitor', text: value }]); const total = products.filter(product => similar(product, value)).length; bot(total ? `Encontrei ${total} material(is) parecido(s) com “${value}”.` : `Não encontrei materiais parecidos com “${value}”. Tente outra palavra, categoria ou série.`); };
  const reset = () => { setTerm(''); setQuery(''); setFilter('all'); setMessages([{ side: 'bot', text: welcome }]); };
  const chips = filter === 'category' ? categories : filter === 'level' ? levels : filter === 'date' ? dates : [];

  return <div className="min-h-[100dvh] bg-slate-100 sm:p-6"><div className="mx-auto grid h-[100dvh] max-w-6xl overflow-hidden bg-white shadow-2xl sm:h-[calc(100dvh-3rem)] sm:grid-cols-[280px_minmax(0,1fr)] sm:rounded-3xl">
    <aside className="hidden overflow-y-auto border-r border-slate-200 bg-slate-50 p-6 sm:block"><Link href={`/loja/${store.slug}`} className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><ArrowLeft className="h-4 w-4" /> Voltar à loja</Link><div className="mt-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-600 text-xl font-black text-white">{store.nome_loja.charAt(0)}</div><h1 className="mt-4 text-lg font-black">{store.nome_loja}</h1><p className="mt-1 text-sm text-slate-500">Atendimento guiado</p></div><div className="mt-8 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-medium text-emerald-900"><strong>{products.length}</strong> materiais publicados<br />Use os filtros para encontrar o seu.</div><div className="mt-5 rounded-2xl border bg-white p-4 text-xs leading-relaxed text-slate-500"><strong className="text-slate-800">Como funciona</strong><br />Mostra somente materiais desta loja. Não usa IA nem cria pedidos automaticamente.</div></aside>
    <main className="flex min-h-0 flex-col"><header className="flex shrink-0 items-center gap-3 bg-emerald-600 px-4 py-4 text-white sm:px-6"><Link href={`/loja/${store.slug}`} className="sm:hidden"><ArrowLeft className="h-5 w-5" /></Link><div className="flex h-10 w-10 items-center justify-center rounded-full bg-white/20 font-black">{store.nome_loja.charAt(0)}</div><div className="min-w-0 flex-1"><h2 className="truncate font-black">{store.nome_loja}</h2><p className="text-xs text-emerald-100">Atendimento automático por filtros</p></div><button onClick={reset} title="Recomeçar atendimento" className="rounded-xl bg-white/15 p-2 hover:bg-white/25"><RotateCcw className="h-4 w-4" /></button></header>
      <div ref={scrollRef} className="min-h-0 flex-1 overflow-y-auto overscroll-contain bg-[#f7f3eb] p-4 sm:p-6"><div className="mx-auto max-w-3xl space-y-4">{messages.map((message, index) => <div key={`${message.text}-${index}`} className={`max-w-xl rounded-2xl px-4 py-3 text-sm leading-relaxed shadow-sm ${message.side === 'visitor' ? 'ml-auto bg-emerald-100 text-emerald-950' : 'bg-white text-slate-800'}`}>{message.text}</div>)}
        <section className="rounded-2xl border border-emerald-100 bg-white p-3 shadow-sm"><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">Como posso ajudar?</p><div className="flex flex-wrap gap-2"><button onClick={() => chooseFilter('Quero ver as ofertas', 'offers')} className="guided-button"><Sparkles /> Ofertas</button><button onClick={() => chooseFilter('Quero filtrar por categoria', 'category')} className="guided-button"><Tag /> Categoria</button><button onClick={() => chooseFilter('Quero filtrar por série', 'level')} className="guided-button"><GraduationCap /> Série</button><button onClick={() => chooseFilter('Quero materiais por data', 'date')} className="guided-button"><CalendarDays /> Data</button></div>{chips.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{chips.map(value => <button key={value} onClick={() => chooseValue(value)} className="choice-button">{value}</button>)}</div>}{filter === 'date' && !chips.length && <p className="mt-3 text-xs text-slate-500">Esta loja ainda não cadastrou temas por data.</p>}</section>
        {(query || filter === 'offers') && <section><div className="mb-2 flex items-center justify-between"><p className="text-xs font-black text-slate-600">{matches.length} resultado(s)</p>{query && <button onClick={() => { setQuery(''); setTerm(''); }} className="text-xs font-bold text-emerald-700">Limpar busca</button>}</div>{matches.length ? <div className="grid gap-3 sm:grid-cols-2">{matches.slice(0, 12).map(product => <Link key={product.id} href={`/loja/${store.slug}/produto/${product.slug || product.id}`} className="rounded-2xl border border-slate-200 bg-white p-3 transition hover:border-emerald-400 hover:shadow-sm"><div className="flex gap-3">{product.capa_url ? <img src={product.capa_url} alt="" className="h-16 w-14 rounded-lg object-cover" /> : <div className="flex h-16 w-14 items-center justify-center rounded-lg bg-slate-100"><PackageSearch className="h-5 w-5 text-slate-400" /></div>}<div className="min-w-0"><p className="line-clamp-2 text-sm font-black text-slate-900">{product.titulo}</p><p className="mt-1 text-sm font-black text-emerald-700">R$ {Number(product.preco).toFixed(2).replace('.', ',')}</p></div></div></Link>)}</div> : <div className="rounded-2xl border border-dashed bg-white p-6 text-center text-sm text-slate-500">Nenhum material parecido encontrado. Tente um termo mais simples.</div>}</section>}
      </div></div><div className="shrink-0 border-t bg-white p-3"><div className="mx-auto flex max-w-3xl gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={term} onChange={event => setTerm(event.target.value)} onKeyDown={event => event.key === 'Enter' && submit()} placeholder="Digite assunto, série, categoria ou data" className="min-h-11 w-full rounded-xl bg-slate-100 py-2 pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-emerald-500" /></div><button onClick={submit} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-600 text-white hover:bg-emerald-700"><Send className="h-5 w-5" /></button></div></div>
    </main></div><style>{`.guided-button{display:inline-flex;align-items:center;gap:.35rem;border-radius:.75rem;background:#ecfdf5;padding:.65rem .8rem;font-size:.75rem;font-weight:800;color:#047857}.guided-button svg{width:14px;height:14px}.guided-button:hover{background:#d1fae5}.choice-button{border-radius:9999px;border:1px solid #d1fae5;background:#fff;padding:.45rem .7rem;font-size:.75rem;font-weight:700;color:#047857}.choice-button:hover{background:#ecfdf5}`}</style></div>;
}
