'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CalendarDays, GraduationCap, MessageCircle, PackageSearch, Send, Sparkles, Tag } from 'lucide-react';
import type { Product, Store } from '@/lib/types';

type Message = { side: 'bot' | 'visitor'; text: string };

export default function GuidedStoreChat({ store, products }: { store: Store; products: Product[] }) {
  const welcome = store.guided_chat_welcome || `Olá! 👋 Bem-vindo à ${store.nome_loja}. Escolha uma opção abaixo para encontrar o material ideal.`;
  const [messages, setMessages] = useState<Message[]>([{ side: 'bot', text: welcome }]);
  const [term, setTerm] = useState('');
  const [filter, setFilter] = useState<'all' | 'category' | 'level' | 'offers'>('all');
  const categories = useMemo(() => Array.from(new Set(products.map(p => p.category?.nome).filter(Boolean))) as string[], [products]);
  const levels = useMemo(() => Array.from(new Set(products.map(p => p.education_level?.nome).filter(Boolean))) as string[], [products]);
  const matches = products.filter(product => {
    const search = term.trim().toLocaleLowerCase('pt-BR');
    if (!search) return true;
    return `${product.titulo} ${product.descricao || ''} ${product.category?.nome || ''} ${product.education_level?.nome || ''}`.toLocaleLowerCase('pt-BR').includes(search);
  }).filter(product => filter !== 'offers' || Number(product.preco_original || 0) > Number(product.preco));
  const reply = (text: string, nextFilter: typeof filter = 'all') => { setMessages(current => [...current, { side: 'visitor', text }, { side: 'bot', text: nextFilter === 'offers' ? 'Estas são as ofertas em destaque desta loja.' : 'Escolha um filtro ou digite o que você procura.' }]); setFilter(nextFilter); };
  const submit = () => { if (!term.trim()) return; setMessages(current => [...current, { side: 'visitor', text: term }, { side: 'bot', text: matches.length ? `Encontrei ${matches.length} material(is). Veja abaixo.` : 'Não encontrei materiais com esse termo. Tente uma categoria, série ou data.' }]); };
  return <div className="min-h-screen bg-slate-100 p-0 sm:p-6"><div className="mx-auto grid min-h-screen max-w-6xl overflow-hidden bg-white shadow-2xl sm:min-h-[720px] sm:grid-cols-[280px_1fr] sm:rounded-3xl">
    <aside className="hidden border-r border-slate-200 bg-slate-50 p-6 sm:block"><Link href={`/loja/${store.slug}`} className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><ArrowLeft className="h-4 w-4" /> Voltar à loja</Link><div className="mt-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-600 text-xl font-black text-white">{store.nome_loja.charAt(0)}</div><h1 className="mt-4 text-lg font-black">{store.nome_loja}</h1><p className="mt-1 text-sm text-slate-500">Atendimento guiado</p></div><div className="mt-8 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-xs font-medium text-emerald-900"><strong>{products.length}</strong> materiais publicados<br />Selecione filtros para encontrar o seu.</div></aside>
    <main className="flex min-h-screen flex-col sm:min-h-0"><header className="flex items-center gap-3 bg-emerald-600 px-4 py-4 text-white sm:px-6"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-white/20 font-black">{store.nome_loja.charAt(0)}</div><div><h2 className="font-black">{store.nome_loja}</h2><p className="text-xs text-emerald-100">Atendimento automático por filtros</p></div></header>
      <div className="flex-1 space-y-4 bg-[#f7f3eb] p-4 sm:p-6">{messages.map((message, index) => <div key={index} className={`max-w-xl rounded-2xl px-4 py-3 text-sm leading-relaxed shadow-sm ${message.side === 'visitor' ? 'ml-auto bg-emerald-100 text-emerald-950' : 'bg-white text-slate-800'}`}>{message.text}</div>)}
        <div className="rounded-2xl bg-white p-3 shadow-sm"><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">Como posso ajudar?</p><div className="flex flex-wrap gap-2"><button onClick={() => reply('Quero ver as ofertas', 'offers')} className="guided-button"><Sparkles /> Ofertas</button><button onClick={() => reply('Quero filtrar por categoria', 'category')} className="guided-button"><Tag /> Categoria</button><button onClick={() => reply('Quero filtrar por série', 'level')} className="guided-button"><GraduationCap /> Série</button><button onClick={() => reply('Quero materiais para uma data', 'all')} className="guided-button"><CalendarDays /> Data</button></div>{filter === 'category' && <div className="mt-3 flex flex-wrap gap-2">{categories.map(category => <button key={category} onClick={() => setTerm(category)} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-700">{category}</button>)}</div>}{filter === 'level' && <div className="mt-3 flex flex-wrap gap-2">{levels.map(level => <button key={level} onClick={() => setTerm(level)} className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-700">{level}</button>)}</div>}</div>
        <div className="grid gap-3 sm:grid-cols-2">{matches.slice(0, 6).map(product => <Link key={product.id} href={`/loja/${store.slug}/produto/${product.slug || product.id}`} className="rounded-2xl border border-slate-200 bg-white p-3 transition hover:border-emerald-400"><div className="flex gap-3">{product.capa_url ? <img src={product.capa_url} alt="" className="h-16 w-14 rounded-lg object-cover" /> : <div className="flex h-16 w-14 items-center justify-center rounded-lg bg-slate-100"><PackageSearch className="h-5 w-5 text-slate-400" /></div>}<div className="min-w-0"><p className="line-clamp-2 text-sm font-black text-slate-900">{product.titulo}</p><p className="mt-1 text-sm font-black text-emerald-700">R$ {Number(product.preco).toFixed(2).replace('.', ',')}</p></div></div></Link>)}</div>
      </div><div className="border-t bg-white p-3"><div className="flex gap-2"><input value={term} onChange={event => setTerm(event.target.value)} onKeyDown={event => event.key === 'Enter' && submit()} placeholder="Digite assunto, série ou data" className="min-h-11 flex-1 rounded-xl bg-slate-100 px-4 text-sm outline-none focus:ring-2 focus:ring-emerald-500" /><button onClick={submit} className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-600 text-white"><Send className="h-5 w-5" /></button></div></div>
    </main></div><style>{`.guided-button{display:inline-flex;align-items:center;gap:.35rem;border-radius:.75rem;background:#ecfdf5;padding:.65rem .8rem;font-size:.75rem;font-weight:800;color:#047857}.guided-button svg{width:14px;height:14px}.guided-button:hover{background:#d1fae5}`}</style></div>;
}
