'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, CalendarDays, GraduationCap, LogIn, PackageSearch, RotateCcw, Search, Send, ShoppingBag, Sparkles, Tag, UserPlus, X, Zap } from 'lucide-react';
import type { Product, Store } from '@/lib/types';
import { useCart } from '@/components/store/CartContext';
import { getAuthenticatedUserRole } from '@/lib/student-service';

type Message = { side: 'bot' | 'visitor'; text: string };
type Filter = 'all' | 'category' | 'level' | 'offers' | 'date';
const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('pt-BR');
const related: Record<string, string[]> = { alfabetizacao: ['alfabetizacao', 'leitura', 'escrita', 'silabas'], matematica: ['matematica', 'numeros', 'contagem', 'adicao', 'tabuada'], portugues: ['portugues', 'leitura', 'escrita', 'gramatica'], meio: ['meio ambiente', 'ambiental', 'natureza'], natal: ['natal', 'dezembro'], pascoa: ['pascoa', 'coelho'] };
function similar(product: Product, raw: string) { const query = normalize(raw).trim(); if (!query) return true; const text = normalize(`${product.titulo} ${product.descricao || ''} ${product.category?.nome || ''} ${product.education_level?.nome || ''} ${(product.seasonal_tags || []).join(' ')}`); return query.split(/\s+/).filter(word => word.length > 1).flatMap(word => related[word] || [word]).some(word => text.includes(word) || text.split(/\W+/).some(candidate => candidate.startsWith(word.slice(0, Math.max(3, word.length - 2))))); }

export default function GuidedStoreChat({ store, products }: { store: Store; products: Product[] }) {
  const router = useRouter();
  const { addToCart } = useCart();
  const welcome = store.guided_chat_welcome || `Olá! 👋 Bem-vindo à ${store.nome_loja}. Escolha uma opção abaixo para encontrar o material ideal.`;
  const [messages, setMessages] = useState<Message[]>([{ side: 'bot', text: welcome }]); const [term, setTerm] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<Filter>('all'); const scrollRef = useRef<HTMLDivElement>(null);
  const [accountPrompt, setAccountPrompt] = useState(false);
  const categories = useMemo(() => Array.from(new Set(products.map(p => p.category?.nome).filter(Boolean))) as string[], [products]); const levels = useMemo(() => Array.from(new Set(products.map(p => p.education_level?.nome).filter(Boolean))) as string[], [products]); const dates = useMemo(() => Array.from(new Set(products.flatMap(p => p.seasonal_tags || []))).slice(0, 12), [products]);
  const matches = useMemo(() => products.filter(product => similar(product, query)).filter(product => filter !== 'offers' || Number(product.preco_original || 0) > Number(product.preco)), [filter, products, query]);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages, filter, query]);
  const bot = (text: string) => setMessages(current => [...current, { side: 'bot', text }]);
  const chooseFilter = (label: string, next: Filter) => { setMessages(current => [...current, { side: 'visitor', text: label }]); setFilter(next); setQuery(''); bot(next === 'offers' ? 'Aqui estão as ofertas desta loja.' : next === 'category' ? 'Escolha uma categoria abaixo.' : next === 'level' ? 'Escolha a série ou nível de ensino.' : 'Escolha uma data ou tema comemorativo.'); };
  const chooseValue = (value: string) => { setTerm(value); setQuery(value); setMessages(current => [...current, { side: 'visitor', text: value }]); bot(`Separei os materiais relacionados a “${value}”.`); };
  const submit = () => { const value = term.trim(); if (!value) return; setQuery(value); setMessages(current => [...current, { side: 'visitor', text: value }]); const total = products.filter(product => similar(product, value)).length; bot(total ? `Encontrei ${total} material(is) parecido(s) com “${value}”.` : `Não encontrei materiais parecidos com “${value}”. Tente outra palavra, categoria ou série.`); };
  const reset = () => { setTerm(''); setQuery(''); setFilter('all'); setMessages([{ side: 'bot', text: welcome }]); };
  const backToMenu = () => { setFilter('all'); setQuery(''); setTerm(''); bot('Sem problema. Escolha uma nova forma de procurar.'); };
  const addProduct = (product: Product) => addToCart({ productId: product.id, title: product.titulo, price: Number(product.preco), storeId: product.store_id, type: product.tipo, isPlr: false, imageUrl: product.capa_url || undefined, quantity: 1 });
  const buyProduct = async (product: Product) => {
    addProduct(product);
    const auth = await getAuthenticatedUserRole();
    const checkoutUrl = `/loja/${store.slug}/checkout`;
    if (!auth.isAuthenticated || auth.role !== 'student') {
      setAccountPrompt(true);
      return;
    }
    router.push(checkoutUrl);
  };
  const chips = filter === 'category' ? categories : filter === 'level' ? levels : filter === 'date' ? dates : [];
  const primaryColor = store.cor_primaria || '#059669';

  return <div className="min-h-[100dvh] bg-[radial-gradient(circle_at_top_left,_#eefaf6,_#eef2f7_55%,_#f8fafc)] sm:p-6"><div className="mx-auto grid h-[100dvh] max-w-6xl overflow-hidden bg-white shadow-2xl sm:h-[calc(100dvh-3rem)] sm:grid-cols-[280px_minmax(0,1fr)] sm:rounded-3xl">
    <aside className="hidden overflow-y-auto border-r border-slate-200 bg-white p-6 sm:block"><Link href={`/loja/${store.slug}`} className="inline-flex items-center gap-1 text-xs font-bold" style={{ color: primaryColor }}><ArrowLeft className="h-4 w-4" /> Voltar à loja</Link><div className="mt-8"><div className="flex h-14 w-14 items-center justify-center rounded-2xl text-xl font-black text-white shadow-lg" style={{ backgroundColor: primaryColor }}>{store.nome_loja.charAt(0)}</div><h1 className="mt-4 text-lg font-black">{store.nome_loja}</h1><p className="mt-1 text-sm text-slate-500">Atendimento guiado</p></div><div className="mt-8 rounded-2xl border p-4 text-xs font-medium" style={{ borderColor: `${primaryColor}33`, backgroundColor: `${primaryColor}12`, color: primaryColor }}><strong>{products.length}</strong> materiais publicados<br />Use os filtros para encontrar o seu.</div></aside>
    <main className="flex min-h-0 flex-col"><header className="flex shrink-0 items-center gap-3 px-4 py-4 text-white sm:px-6" style={{ backgroundColor: primaryColor }}><Link href={`/loja/${store.slug}`} className="sm:hidden"><ArrowLeft className="h-5 w-5" /></Link><div className="flex h-10 w-10 items-center justify-center rounded-full bg-white/20 font-black">{store.nome_loja.charAt(0)}</div><div className="min-w-0 flex-1"><h2 className="truncate font-black">{store.nome_loja}</h2><p className="text-xs text-white/80">Encontre materiais e compre com segurança</p></div><button onClick={reset} title="Recomeçar atendimento" className="rounded-xl bg-white/15 p-2 hover:bg-white/25"><RotateCcw className="h-4 w-4" /></button></header>
      <div ref={scrollRef} className="min-h-0 flex-1 overflow-y-auto overscroll-contain bg-[#f7f3eb] p-4 sm:p-6"><div className="mx-auto max-w-3xl space-y-4">{messages.map((message, index) => <div key={`${message.text}-${index}`} className={`max-w-xl rounded-2xl px-4 py-3 text-sm leading-relaxed shadow-sm ${message.side === 'visitor' ? 'ml-auto bg-emerald-100 text-emerald-950' : 'bg-white text-slate-800'}`}>{message.text}</div>)}
        <section className="rounded-2xl border border-emerald-100 bg-white p-3 shadow-sm">{filter === 'all' ? <><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">Como posso ajudar?</p><div className="flex flex-wrap gap-2"><button onClick={() => chooseFilter('Quero ver as ofertas', 'offers')} className="guided-button"><Sparkles /> Ofertas</button><button onClick={() => chooseFilter('Quero filtrar por categoria', 'category')} className="guided-button"><Tag /> Categoria</button><button onClick={() => chooseFilter('Quero filtrar por série', 'level')} className="guided-button"><GraduationCap /> Série</button><button onClick={() => chooseFilter('Quero materiais por data', 'date')} className="guided-button"><CalendarDays /> Data</button></div></> : <><div className="mb-3 flex items-center justify-between"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{filter === 'category' ? 'Escolha a categoria' : filter === 'level' ? 'Escolha a série' : filter === 'date' ? 'Escolha a data' : 'Ofertas da loja'}</p><button onClick={backToMenu} className="inline-flex items-center gap-1 text-xs font-black text-emerald-700"><ArrowLeft className="h-3.5 w-3.5" /> Voltar ao menu</button></div>{chips.length > 0 && <div className="flex flex-wrap gap-2">{chips.map(value => <button key={value} onClick={() => chooseValue(value)} className="choice-button">{value}</button>)}</div>}{filter === 'date' && !chips.length && <p className="text-xs text-slate-500">Esta loja ainda não cadastrou temas por data.</p>}</>}</section>
        {(query || filter === 'offers') && <section><div className="mb-2 flex items-center justify-between"><p className="text-xs font-black text-slate-600">{matches.length} resultado(s)</p>{query && <button onClick={() => { setQuery(''); setTerm(''); }} className="text-xs font-bold text-emerald-700">Limpar busca</button>}</div>{matches.length ? <div className="grid gap-3 sm:grid-cols-2">{matches.slice(0, 12).map(product => <article key={product.id} className="rounded-2xl border border-slate-200 bg-white p-3 transition hover:border-emerald-400 hover:shadow-sm"><Link href={`/loja/${store.slug}/produto/${product.slug || product.id}`} className="flex gap-3">{product.capa_url ? <img src={product.capa_url} alt="" className="h-16 w-14 rounded-lg object-cover" /> : <div className="flex h-16 w-14 items-center justify-center rounded-lg bg-slate-100"><PackageSearch className="h-5 w-5 text-slate-400" /></div>}<div className="min-w-0"><p className="line-clamp-2 text-sm font-black text-slate-900">{product.titulo}</p><p className="mt-1 text-sm font-black text-emerald-700">R$ {Number(product.preco).toFixed(2).replace('.', ',')}</p></div></Link><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => addProduct(product)} className="inline-flex min-h-10 items-center justify-center gap-1 rounded-xl bg-slate-100 px-2 text-xs font-black text-slate-700 hover:bg-slate-200"><ShoppingBag className="h-4 w-4" /> Adicionar</button><button onClick={() => buyProduct(product)} className="inline-flex min-h-10 items-center justify-center gap-1 rounded-xl bg-emerald-600 px-2 text-xs font-black text-white hover:bg-emerald-700"><Zap className="h-4 w-4" /> Comprar</button></div></article>)}</div> : <div className="rounded-2xl border border-dashed bg-white p-6 text-center text-sm text-slate-500">Nenhum material parecido encontrado. Tente um termo mais simples.</div>}</section>}
      </div></div><div className="shrink-0 border-t bg-white p-3"><div className="mx-auto flex max-w-3xl gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={term} onChange={event => setTerm(event.target.value)} onKeyDown={event => event.key === 'Enter' && submit()} placeholder="Digite assunto, série, categoria ou data" className="min-h-11 w-full rounded-xl bg-slate-100 py-2 pl-10 pr-3 text-sm outline-none" /></div><button onClick={submit} style={{ backgroundColor: primaryColor }} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-white"><Send className="h-5 w-5" /></button></div></div>
    </main></div>{accountPrompt && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-xl font-black">Finalizar sua compra</h3><p className="mt-2 text-sm text-slate-600">Para proteger sua entrega, entre ou crie gratuitamente sua conta de cliente.</p></div><button onClick={() => setAccountPrompt(false)} className="rounded-lg p-1 text-slate-400"><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={() => router.push(`/cliente/login?returnTo=${encodeURIComponent(`/loja/${store.slug}/checkout`)}&action=buy`)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl text-sm font-black text-white" style={{ backgroundColor: primaryColor }}><LogIn className="h-4 w-4" /> Já tenho conta</button><button onClick={() => router.push(`/cliente/cadastro?returnTo=${encodeURIComponent(`/loja/${store.slug}/checkout`)}&action=buy`)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border text-sm font-black" style={{ borderColor: primaryColor, color: primaryColor }}><UserPlus className="h-4 w-4" /> Criar conta</button></div></div></div>}<style>{`.guided-button{display:inline-flex;align-items:center;gap:.35rem;border-radius:.75rem;background:${primaryColor}12;padding:.65rem .8rem;font-size:.75rem;font-weight:800;color:${primaryColor}}.guided-button svg{width:14px;height:14px}.choice-button{border-radius:9999px;border:1px solid ${primaryColor}33;background:#fff;padding:.45rem .7rem;font-size:.75rem;font-weight:700;color:${primaryColor}}`}</style></div>;
}
