'use client';

import { useEffect, useMemo, useState } from 'react';
import { Download, Loader2, Mail, Search, Users } from 'lucide-react';
import { toast } from 'sonner';

type Lead = { id: string; email: string; source: string; consented_at: string; created_at: string };
export default function AdminLeadsPage() {
  const [leads, setLeads] = useState<Lead[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState('');
  const load = async () => { setLoading(true); try { const response = await fetch('/api/admin/leads'); const data = await response.json(); if (!response.ok) throw new Error(data.error); setLeads(data.leads || []); } catch (error: any) { toast.error(error.message || 'Não foi possível carregar os leads.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => leads.filter((lead) => lead.email.toLowerCase().includes(query.trim().toLowerCase())), [leads, query]);
  const exportCsv = async () => { try { const response = await fetch('/api/admin/leads?export=csv'); if (!response.ok) throw new Error(); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'leads-educalizando.csv'; link.click(); URL.revokeObjectURL(url); } catch { toast.error('Não foi possível exportar os leads.'); } };
  const date = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));
  return <div className="space-y-6"><div className="flex flex-col gap-4 rounded-xl border border-slate-800 bg-slate-900 p-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Users className="text-blue-500" /> Leads e contatos</h1><p className="mt-1 text-sm text-slate-400">Pessoas que pediram novidades, guias e materiais pedagógicos.</p></div><button onClick={exportCsv} disabled={!leads.length} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-50"><Download className="h-4 w-4" /> Exportar CSV</button></div><div className="rounded-xl border border-slate-800 bg-slate-900"><div className="flex flex-col gap-3 border-b border-slate-800 p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-bold text-slate-200">{filtered.length} contato{filtered.length === 1 ? '' : 's'}</p><label className="flex min-h-11 items-center gap-2 rounded-lg border border-slate-700 bg-slate-950 px-3 sm:w-72"><Search className="h-4 w-4 text-slate-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por e-mail" className="min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none" /></label></div>{loading ? <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-blue-500" /></div> : <div className="divide-y divide-slate-800">{filtered.length ? filtered.map((lead) => <div key={lead.id} className="flex flex-col gap-1 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><Mail className="h-4 w-4 text-blue-400" /><span className="font-bold text-slate-100">{lead.email}</span></div><div className="mt-2 flex gap-3 text-xs sm:mt-0"><span className="rounded-full bg-slate-800 px-2 py-1 font-bold text-slate-300">{lead.source || 'site'}</span><span className="text-slate-500">{date(lead.created_at)}</span></div></div>) : <p className="p-10 text-center text-sm text-slate-500">Nenhum contato encontrado.</p>}</div>}</div></div>;
}
