'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Copy, ExternalLink, MessagesSquare, Save, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { getCurrentCreatorStore, updateStore } from '@/lib/store-service';
import type { Store } from '@/lib/types';

export default function AtendimentoPage() {
  const [store, setStore] = useState<Store | null>(null); const [welcome, setWelcome] = useState(''); const [enabled, setEnabled] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { getCurrentCreatorStore().then(value => { setStore(value); setWelcome(value.guided_chat_welcome || `Olá! 👋 Bem-vindo à ${value.nome_loja}. Escolha uma opção abaixo para encontrar o material ideal.`); setEnabled(value.guided_chat_enabled !== false); }); }, []);
  const url = store ? `${typeof window !== 'undefined' ? window.location.origin : ''}/atendimento/${store.slug}` : '';
  const save = async () => { if (!store) return; setSaving(true); try { const updated = await updateStore(store.id, { guided_chat_enabled: enabled, guided_chat_welcome: welcome }); setStore(updated); toast.success('Atendimento guiado salvo.'); } catch (error: any) { toast.error(error.message || 'Não foi possível salvar.'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl space-y-6"><section className="rounded-3xl bg-gradient-to-br from-emerald-600 to-teal-700 p-6 text-white sm:p-8"><p className="mb-2 inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-black"><Sparkles className="h-4 w-4" /> SEM IA · 100% POR FILTROS</p><h1 className="text-3xl font-black">Atendimento Guiado</h1><p className="mt-2 max-w-2xl text-sm text-emerald-50">Um miniatendimento da sua loja que orienta clientes por botões, categorias, séries, datas e ofertas — sem respostas inventadas.</p></section>{store && <><section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">Canal de atendimento</h2><p className="text-sm text-slate-500">Use este link na bio, campanhas ou WhatsApp.</p></div><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} className="h-5 w-5 accent-emerald-600" /> Atendimento ativo</label></div><div className="mt-4 flex gap-2"><input readOnly value={url} className="min-h-11 flex-1 rounded-xl border bg-slate-50 px-3 text-sm" /><button onClick={() => navigator.clipboard.writeText(url).then(() => toast.success('Link copiado.'))} className="rounded-xl border px-3 text-slate-700"><Copy className="h-4 w-4" /></button><Link href={`/atendimento/${store.slug}`} target="_blank" className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-black text-white"><ExternalLink className="h-4 w-4" /> Abrir</Link></div></section><section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MessagesSquare className="h-5 w-5 text-emerald-600" /><h2 className="font-black">Mensagem inicial</h2></div><p className="mt-1 text-sm text-slate-500">Aparece como a primeira resposta para todos os visitantes.</p><textarea value={welcome} maxLength={500} onChange={event => setWelcome(event.target.value)} className="mt-4 min-h-32 w-full rounded-2xl border p-4 text-sm outline-none focus:ring-2 focus:ring-emerald-500" /><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-500">{welcome.length}/500</span><button onClick={save} disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-600 px-5 text-sm font-black text-white disabled:opacity-60"><Save className="h-4 w-4" /> {saving ? 'Salvando...' : 'Salvar atendimento'}</button></div></section><section className="grid gap-3 sm:grid-cols-3">{['Botões de categoria','Filtros por série','Ofertas e busca livre'].map(item => <div key={item} className="rounded-2xl border bg-white p-4 text-sm font-bold text-slate-800">✓ {item}</div>)}</section></>}</div>;
}
