'use client';
import { Product } from '@/lib/types';
import { ArrowUpRight,Package } from 'lucide-react';

export function SeoChangePreview({ item, product }: { item: { title: string; coverUrl: string | null; recommendedTitle: string; description: string; tags: string[]; themes: string[]; quickWins: string[] }; product?: Product }) {
  const currentTitle = product?.titulo || 'Não informado';
  const currentDescription = product?.descricao || 'Sem descrição';
  const currentTags = product?.tags || [];
  const currentThemes = product?.seasonal_tags || [];
  const change = (label: string, before: string, after: string) => <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-xs text-slate-500"><strong>Atual:</strong> {before}</p><p className="mt-2 whitespace-pre-line text-sm leading-6 text-violet-950"><strong>Será alterado para:</strong> {after}</p></div>;
  return <article className="rounded-2xl border border-slate-200 p-4 sm:p-5"><div className="flex items-center gap-3"><div className="h-12 w-12 overflow-hidden rounded-lg bg-violet-50">{item.coverUrl ? <img src={item.coverUrl} alt="" className="h-full w-full object-cover" /> : <Package className="m-3 h-6 w-6 text-violet-500" />}</div><div><h3 className="font-black text-slate-900">{item.title}</h3><p className="mt-1 text-xs font-bold text-emerald-700">A IA vai melhorar a busca e a apresentação deste material.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{change('Título', currentTitle, item.recommendedTitle || currentTitle)}{change('Tags de busca', currentTags.join(', ') || 'Nenhuma tag', item.tags.join(', ') || 'Manter sem tags')}<div className="sm:col-span-2">{change('Descrição de venda', currentDescription, item.description || currentDescription)}</div>{change('Temas pedagógicos', currentThemes.join(', ') || 'Nenhum tema', item.themes.join(', ') || 'Manter temas atuais')}<div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-emerald-700">Por que estas alterações</p><ul className="mt-2 space-y-1 text-xs leading-5 text-emerald-950">{item.quickWins.map(action => <li key={action}>• {action}</li>)}</ul></div></div></article>;
}

export function SeoAuditCard({ item, selected, onToggle, onOptimize, onOptimizePlr }: { item: { title: string; score: number; coverUrl: string | null; issues: string[]; quickWins: string[]; recommendedTitle: string; suggestedCaption: string; metaDescription: string }; selected: boolean; onToggle: () => void; onOptimize: () => void; onOptimizePlr?: () => void }) {
  return <article className={`relative overflow-hidden rounded-2xl border bg-white shadow-sm transition ${selected ? 'border-violet-500 ring-2 ring-violet-200' : 'border-slate-200'}`}><label className="absolute right-3 top-3 z-10 flex cursor-pointer items-center gap-2 rounded-full bg-white px-2 py-1 text-[10px] font-black text-violet-800 shadow-sm ring-1 ring-violet-200"><input type="checkbox" checked={selected} onChange={onToggle} className="h-4 w-4 accent-violet-600" /> Selecionar</label><div className="flex gap-3 border-b border-slate-100 p-4 pr-28"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-violet-50">{item.coverUrl ? <img src={item.coverUrl} alt={`Capa de ${item.title}`} className="h-full w-full object-cover" /> : <Package className="m-5 h-6 w-6 text-violet-500" />}</div><div className="min-w-0 flex-1"><p className="line-clamp-2 text-sm font-black text-slate-900">{item.title}</p><p className={`mt-1 text-xs font-bold ${selected ? 'text-violet-700' : 'text-amber-700'}`}>SEO {item.score}/100</p></div></div><div className="p-4"><div className="grid gap-3 sm:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">O que precisa atenção</p><ul className="mt-1.5 space-y-1 text-xs leading-5 text-slate-600">{item.issues.slice(0, 3).map(issue => <li key={issue}>• {issue}</li>)}</ul></div><div><p className="text-[10px] font-black uppercase tracking-wider text-emerald-700">Sugestões da IA</p><ul className="mt-1.5 space-y-1 text-xs leading-5 text-slate-600">{item.quickWins.slice(0, 3).map(win => <li key={win}>• {win}</li>)}</ul></div></div>{item.recommendedTitle && <p className="mt-3 rounded-xl bg-violet-50 px-3 py-2 text-xs leading-5 text-violet-900"><strong>Título sugerido:</strong> {item.recommendedTitle}</p>}{item.suggestedCaption && <p className="mt-2 rounded-xl bg-pink-50 px-3 py-2 text-xs leading-5 text-pink-950"><strong>Legenda sugerida:</strong> {item.suggestedCaption}</p>}{item.metaDescription && <p className="mt-2 rounded-xl bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-600"><strong>Resumo para busca:</strong> {item.metaDescription}</p>}<div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={onOptimize} className="inline-flex min-h-10 items-center gap-1 rounded-xl bg-violet-600 px-3 text-xs font-black text-white transition hover:bg-violet-700">Otimizar produto final <ArrowUpRight className="h-3.5 w-3.5" /></button>{onOptimizePlr && <button type="button" onClick={onOptimizePlr} className="inline-flex min-h-10 items-center gap-1 rounded-xl border border-amber-300 bg-amber-50 px-3 text-xs font-black text-amber-900 transition hover:bg-amber-100">Otimizar PLR <ArrowUpRight className="h-3.5 w-3.5" /></button>}</div></div></article>;
}
