'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, BookOpen, CheckCircle2, GraduationCap, Search, ShoppingBag, Sparkles, Star, Tag, Zap } from 'lucide-react';
import type { StoreListingProduct, StoreThemeProps } from '@/lib/types';
import { useCart } from '@/components/store/CartContext';

type Variant = 'minimalist' | 'netflix' | 'linktree' | 'pinterest';

const formatPrice = (price: number) => `R$ ${Number(price || 0).toFixed(2).replace('.', ',')}`;

export default function StoreExperienceTheme({ variant, ...props }: StoreThemeProps & { variant: Variant }) {
  const { store, filteredProducts, categories, educationLevels, selectedCategory, setSelectedCategory, selectedEducation, setSelectedEducation, searchFilter, setSearchFilter } = props;
  const { addToCart, setIsOpen } = useCart();
  const primary = store.cor_primaria || '#2563eb';
  const dark = variant === 'netflix';
  const linkBio = variant === 'linktree';
  const pinterest = variant === 'pinterest';
  const buttonRadius = store.button_style === 'pill' ? 'rounded-full' : store.button_style === 'square' ? 'rounded-md' : 'rounded-xl';
  const visibleProducts = filteredProducts.slice(0, 24);

  const add = (product: StoreListingProduct) => {
    addToCart({ productId: product.id, title: product.titulo, price: Number(product.preco), storeId: store.id, type: product.tipo, isPlr: product.listing_mode === 'plr', imageUrl: product.capa_url || undefined, quantity: 1 });
    setIsOpen(true);
  };

  const buy = (product: StoreListingProduct) => {
    addToCart({ productId: product.id, title: product.titulo, price: Number(product.preco), storeId: store.id, type: product.tipo, isPlr: product.listing_mode === 'plr', imageUrl: product.capa_url || undefined, quantity: 1 });
    window.location.assign(`/loja/${store.slug}/checkout`);
  };

  const ProductCard = ({ product, index, compact = false }: { product: StoreListingProduct; index: number; compact?: boolean }) => <motion.article initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: Math.min(index * .04, .3) }} className={`group min-w-0 overflow-hidden border transition hover:-translate-y-1 hover:shadow-xl ${dark ? 'border-white/10 bg-white/5 text-white' : 'border-slate-200 bg-white text-slate-900'} ${buttonRadius}`}>
    <Link href={`/loja/${store.slug}/produto/${product.slug || product.id}`} className={`relative block overflow-hidden bg-slate-100 ${compact ? 'aspect-square' : 'aspect-[4/3]'}`}>
      {product.capa_url ? <img src={product.capa_url} alt={product.titulo} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="flex h-full items-center justify-center text-sm text-slate-400"><BookOpen /></div>}
      {Number(product.preco_original || 0) > Number(product.preco) && <span className="absolute left-3 top-3 rounded-full bg-rose-500 px-2 py-1 text-[10px] font-black text-white">OFERTA</span>}
    </Link>
    <div className={`min-w-0 ${compact ? 'p-3' : 'p-4 sm:p-5'}`}><div className="mb-2 flex items-center gap-1 text-[10px] font-bold" style={{ color: primary }}><Sparkles className="h-3 w-3" /> Material digital</div><Link href={`/loja/${store.slug}/produto/${product.slug || product.id}`}><h3 className={`font-black leading-tight ${compact ? 'line-clamp-2 text-sm' : 'line-clamp-2 text-base'}`}>{product.titulo}</h3></Link>{!compact && product.descricao && <p className={`mt-2 line-clamp-2 text-xs ${dark ? 'text-slate-300' : 'text-slate-500'}`}>{product.descricao}</p>}<div className="mt-4 flex items-end justify-between gap-2"><div><p className={`text-[10px] font-bold uppercase ${dark ? 'text-slate-400' : 'text-slate-400'}`}>Acesso imediato</p><p className="text-lg font-black" style={{ color: primary }}>{formatPrice(Number(product.preco))}</p></div><button onClick={() => add(product)} aria-label={`Adicionar ${product.titulo} ao carrinho`} className={`${buttonRadius} inline-flex h-10 w-10 shrink-0 items-center justify-center border ${dark ? 'border-white/15 bg-white/10' : 'border-slate-200 bg-slate-50'}`}><ShoppingBag className="h-4 w-4" /></button></div>{!compact && <button onClick={() => buy(product)} className={`${buttonRadius} mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 text-xs font-black text-white`} style={{ backgroundColor: primary }}><Zap className="h-4 w-4" /> Comprar agora</button>}</div>
  </motion.article>;

  return <div className={`min-h-screen ${dark ? 'bg-[#080b16] text-white' : pinterest ? 'bg-[#fff8f7] text-slate-900' : linkBio ? 'bg-gradient-to-b from-slate-50 to-white text-slate-900' : 'bg-white text-slate-900'}`}>
    <header className={`sticky top-0 z-30 border-b backdrop-blur ${dark ? 'border-white/10 bg-[#080b16]/90' : 'border-slate-200/80 bg-white/90'}`}><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6"><Link href={`/loja/${store.slug}`} className="flex min-w-0 items-center gap-2"><div className={`${buttonRadius} flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden text-sm font-black text-white`} style={{ backgroundColor: primary }}>{store.logo_url ? <img src={store.logo_url} alt="" className="h-full w-full object-cover" /> : store.nome_loja.charAt(0)}</div><span className="truncate font-black">{store.nome_loja}</span></Link><button onClick={() => setIsOpen(true)} className={`${buttonRadius} inline-flex min-h-10 items-center gap-2 px-3 text-xs font-black text-white`} style={{ backgroundColor: primary }}><ShoppingBag className="h-4 w-4" /> Carrinho</button></div></header>
    <main className={`mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12 ${linkBio ? 'max-w-xl' : ''}`}>
      <section className={`${linkBio ? 'text-center' : 'grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center'} ${dark ? 'rounded-[2rem] bg-gradient-to-br from-indigo-950 via-[#101a39] to-slate-950 p-6 sm:p-10' : pinterest ? 'rounded-[2rem] bg-gradient-to-br from-rose-100 via-white to-amber-50 p-6 sm:p-10' : 'py-4 sm:py-10'}`}>
        <div>{linkBio && <div className={`${buttonRadius} mx-auto mb-5 flex h-20 w-20 items-center justify-center overflow-hidden text-3xl font-black text-white`} style={{ backgroundColor: primary }}>{store.logo_url ? <img src={store.logo_url} alt="" className="h-full w-full object-cover" /> : store.nome_loja.charAt(0)}</div>}<span className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-[10px] font-black uppercase tracking-wider" style={{ backgroundColor: `${primary}18`, color: primary }}><CheckCircle2 className="h-3.5 w-3.5" /> Materiais para educadores</span><h1 className={`mt-4 font-black tracking-tight ${linkBio ? 'text-3xl' : 'text-4xl sm:text-6xl'}`}>{store.welcome_message || `Materiais que facilitam o seu planejamento.`}</h1><p className={`mt-4 max-w-xl text-sm leading-relaxed ${dark ? 'text-slate-300' : 'text-slate-600'} ${linkBio ? 'mx-auto' : ''}`}>{store.descricao || 'Explore recursos didáticos digitais selecionados para deixar cada aula mais leve e significativa.'}</p><div className={`mt-6 flex flex-wrap gap-2 ${linkBio ? 'justify-center' : ''}`}><button onClick={() => document.getElementById('catalogo')?.scrollIntoView({ behavior: 'smooth' })} className={`${buttonRadius} inline-flex min-h-11 items-center gap-2 px-4 text-sm font-black text-white`} style={{ backgroundColor: primary }}>Ver materiais <ArrowRight className="h-4 w-4" /></button>{store.whatsapp && <a href={`https://wa.me/55${store.whatsapp.replace(/\D/g, '')}`} target="_blank" rel="noopener noreferrer" className={`${buttonRadius} inline-flex min-h-11 items-center gap-2 border px-4 text-sm font-black ${dark ? 'border-white/20' : 'border-slate-200'}`}>Falar com criador</a>}</div></div>
        {!linkBio && <div className={`relative overflow-hidden ${buttonRadius} ${dark ? 'bg-white/5' : 'bg-slate-100'} p-3`}><div className="grid grid-cols-2 gap-3">{visibleProducts.slice(0, 4).map((product, index) => <div key={product.id} className={index === 0 ? 'col-span-2' : ''}>{product.capa_url ? <img src={product.capa_url} alt="" className={`w-full object-cover ${buttonRadius} ${index === 0 ? 'h-48 sm:h-56' : 'h-24 sm:h-28'}`} /> : <div className={`h-24 ${buttonRadius} bg-white/20`} />}</div>)}</div></div>}
      </section>
      <section id="catalogo" className="mt-10 scroll-mt-24"><div className={`mb-5 flex flex-col gap-3 ${linkBio ? 'items-center' : 'sm:flex-row sm:items-end sm:justify-between'}`}><div><p className="text-xs font-black uppercase tracking-[.18em]" style={{ color: primary }}>Catálogo da loja</p><h2 className="mt-1 text-2xl font-black">{variant === 'netflix' ? 'Continue explorando' : variant === 'pinterest' ? 'Inspirações para a sua turma' : 'Encontre o material ideal'}</h2></div><label className={`relative block ${linkBio ? 'w-full' : 'sm:w-80'}`}><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={searchFilter} onChange={(event) => setSearchFilter(event.target.value)} placeholder="Busque por assunto ou tema" className={`${buttonRadius} min-h-11 w-full border bg-white py-2 pl-10 pr-3 text-sm text-slate-900 outline-none focus:ring-2`} style={{ borderColor: `${primary}44` }} /></label></div><div className={`mb-6 flex gap-2 overflow-x-auto pb-1 ${linkBio ? 'justify-start' : ''}`}><button onClick={() => { setSelectedCategory('all'); setSelectedEducation('all'); }} className={`${buttonRadius} shrink-0 px-3 py-2 text-xs font-black`} style={{ backgroundColor: selectedCategory === 'all' && selectedEducation === 'all' ? primary : `${primary}12`, color: selectedCategory === 'all' && selectedEducation === 'all' ? '#fff' : primary }}>Todos</button>{categories.map(category => <button key={category.id} onClick={() => setSelectedCategory(category.id)} className={`${buttonRadius} shrink-0 border px-3 py-2 text-xs font-bold`} style={{ borderColor: `${primary}33`, color: primary }}>{category.nome}</button>)}{educationLevels.slice(0, 4).map(level => <button key={level.id} onClick={() => setSelectedEducation(level.id)} className={`${buttonRadius} shrink-0 border px-3 py-2 text-xs font-bold`} style={{ borderColor: `${primary}33`, color: primary }}>{level.nome}</button>)}</div>
        {visibleProducts.length ? <div className={linkBio ? 'space-y-3' : pinterest ? 'columns-1 gap-4 sm:columns-2 lg:columns-3 xl:columns-4' : dark ? 'grid gap-4 sm:grid-cols-2 lg:grid-cols-4' : 'grid gap-5 sm:grid-cols-2 lg:grid-cols-3'}>{visibleProducts.map((product, index) => <div key={`${product.id}-${product.listing_mode || 'standard'}`} className={pinterest ? 'mb-4 break-inside-avoid' : ''}><ProductCard product={product} index={index} compact={linkBio || pinterest || dark} /></div>)}</div> : <div className={`${buttonRadius} border border-dashed p-12 text-center text-sm text-slate-500`}>Nenhum material encontrado. Tente outro tema.</div>}
      </section>
    </main>
  </div>;
}
