'use client';

import { ArrowDownToLine,ArrowUpFromLine,CheckCircle2,CloudCog,Loader2,PackageCheck,PauseCircle,RefreshCw,ShoppingCart,Unplug,X,Zap } from 'lucide-react';
import { useCallback,useEffect,useState,type ReactNode } from 'react';
import { toast } from 'sonner';

type Integration = { id: string; site_url: string; status: 'active' | 'paused' | 'error'; sync_products_to_woo: boolean; sync_products_from_woo: boolean; sync_orders_from_woo: boolean; last_sync_at: string | null; last_error: string | null };
type Log = { id: string; entity_type: string; status: string; processed_count: number; failed_count: number; message: string | null; created_at: string };
type WooOrder = { id: string; woo_order_id: number; status: string; currency: string | null; total: number; customer_name: string | null; customer_email: string | null; date_created: string | null };
type Payload = { integration: Integration | null; logs: Log[]; orders: WooOrder[]; orderCount: number; error?: string };
type WooCatalogProduct = { id: number; name: string; price: number; status: string; image: string | null; stockStatus: string | null; stockQuantity: number | null; alreadyImported: boolean; localProductId: string | null };

export default function WooCommercePage() {
  const [data,setData] = useState<Payload | null>(null); const [loading,setLoading] = useState(true); const [saving,setSaving] = useState(false); const [syncing,setSyncing] = useState('');
  const [catalog,setCatalog] = useState<WooCatalogProduct[]>([]); const [catalogOpen,setCatalogOpen] = useState(false); const [catalogLoading,setCatalogLoading] = useState(false); const [selectedIds,setSelectedIds] = useState<number[]>([]);
  const [siteUrl,setSiteUrl] = useState(''); const [consumerKey,setConsumerKey] = useState(''); const [consumerSecret,setConsumerSecret] = useState('');
  const load = useCallback(async () => { try { const response = await fetch('/api/creator/woocommerce', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível carregar.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const connect = async () => { setSaving(true); try { const response = await fetch('/api/creator/woocommerce', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ siteUrl, consumerKey, consumerSecret }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setConsumerKey(''); setConsumerSecret(''); toast.success(`WooCommerce conectado. ${payload.webhooksConfigured} automações configuradas.`); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível conectar.'); } finally { setSaving(false); } };
  const update = async (changes: Record<string, boolean | string>) => { const response = await fetch('/api/creator/woocommerce', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(changes) }); const payload = await response.json(); if (!response.ok) return toast.error(payload.error || 'Não foi possível salvar.'); await load(); };
  const sync = async (direction: string, productIds?: number[]) => { setSyncing(direction); try { const response = await fetch('/api/creator/woocommerce/sync', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ direction, productIds }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); toast.success(`${payload.processed} item(ns) sincronizado(s)${payload.failed ? ` e ${payload.failed} falha(s)` : ''}.`); if (direction === 'from_woo') { setCatalogOpen(false); setSelectedIds([]); } await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'A sincronização falhou.'); } finally { setSyncing(''); } };
  const openCatalog = async () => { setCatalogOpen(true); setCatalogLoading(true); try { const response = await fetch('/api/creator/woocommerce/catalog', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setCatalog(payload.products || []); setSelectedIds([]); } catch (error) { setCatalogOpen(false); toast.error(error instanceof Error ? error.message : 'Não foi possível carregar o catálogo.'); } finally { setCatalogLoading(false); } };
  const disconnect = async () => { if (!window.confirm('Desconectar o WooCommerce desta loja? O histórico importado será removido.')) return; const response = await fetch('/api/creator/woocommerce', { method: 'DELETE' }); if (response.ok) { toast.success('Integração desconectada.'); await load(); } else toast.error('Não foi possível desconectar.'); };
  if (loading) return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-violet-600" /></div>;
  const integration = data?.integration;
  return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="rounded-3xl bg-gradient-to-br from-violet-700 via-purple-700 to-fuchsia-700 p-6 text-white shadow-xl sm:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl bg-white/15 p-3"><CloudCog className="h-8 w-8" /></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-100">Integrações da loja</p><h1 className="mt-1 text-3xl font-black">WooCommerce</h1><p className="mt-2 max-w-3xl text-sm text-violet-100">Conecte sua loja, sincronize produtos nos dois sentidos e acompanhe pedidos do WooCommerce dentro do painel.</p></div></div></header>
    {!integration ? <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-black text-slate-900">Conectar minha loja WooCommerce</h2><p className="mt-2 text-sm text-slate-600">No WordPress, acesse WooCommerce → Configurações → Avançado → REST API e crie uma chave com permissão de leitura e escrita.</p><div className="mt-6 grid gap-4"><label className="text-sm font-bold text-slate-700">Endereço da loja<input type="url" value={siteUrl} onChange={e => setSiteUrl(e.target.value)} placeholder="https://minhaloja.com.br" className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-violet-500" /></label><label className="text-sm font-bold text-slate-700">Consumer Key<input value={consumerKey} onChange={e => setConsumerKey(e.target.value)} placeholder="ck_..." className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 font-mono text-sm font-normal outline-none focus:border-violet-500" /></label><label className="text-sm font-bold text-slate-700">Consumer Secret<input type="password" value={consumerSecret} onChange={e => setConsumerSecret(e.target.value)} placeholder="cs_..." className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 font-mono text-sm font-normal outline-none focus:border-violet-500" /></label><button onClick={() => void connect()} disabled={saving || !siteUrl || !consumerKey || !consumerSecret} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-violet-600 px-6 text-sm font-black text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Zap className="h-4 w-4" />}Testar e conectar</button></div></section> : <>
      <section className="rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 h-6 w-6 text-emerald-600" /><div><h2 className="font-black text-emerald-950">Loja conectada</h2><a href={integration.site_url} target="_blank" rel="noreferrer" className="text-sm text-emerald-700 underline">{integration.site_url}</a><p className="mt-1 text-xs text-emerald-800">{integration.last_sync_at ? `Última sincronização: ${new Date(integration.last_sync_at).toLocaleString('pt-BR')}` : 'Ainda não sincronizada.'}</p></div></div><button onClick={() => void update({ status: integration.status === 'active' ? 'paused' : 'active' })} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-300 bg-white px-4 text-sm font-black text-emerald-800"><PauseCircle className="h-4 w-4" />{integration.status === 'active' ? 'Pausar' : 'Reativar'}</button></div>{integration.last_error && <p className="mt-4 rounded-xl bg-amber-100 p-3 text-sm font-bold text-amber-900">{integration.last_error}</p>}</section>
      <section className="grid gap-4 md:grid-cols-3"><SyncCard icon={<ArrowUpFromLine />} title="Educalizando → Woo" description="Cria ou atualiza no WooCommerce os produtos desta loja." enabled={integration.sync_products_to_woo} busy={syncing === 'to_woo'} onToggle={value => void update({ sync_products_to_woo: value })} onRun={() => void sync('to_woo')} /><SyncCard icon={<ArrowDownToLine />} title="Woo → Educalizando" description="Revise o catálogo e escolha exatamente quais produtos deseja importar." enabled={integration.sync_products_from_woo} busy={catalogLoading} onToggle={value => void update({ sync_products_from_woo: value })} onRun={() => void openCatalog()} actionLabel="Escolher produtos" /><SyncCard icon={<ShoppingCart />} title="Pedidos do Woo" description={`${data?.orderCount || 0} pedido(s) espelhado(s) no painel.`} enabled={integration.sync_orders_from_woo} busy={syncing === 'orders'} onToggle={value => void update({ sync_orders_from_woo: value })} onRun={() => void sync('orders')} /></section>
      {catalogOpen && <WooImportPicker products={catalog} selectedIds={selectedIds} loading={catalogLoading} importing={syncing === 'from_woo'} onClose={() => setCatalogOpen(false)} onChange={setSelectedIds} onImport={() => void sync('from_woo', selectedIds)} />}
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Pedidos recentes do WooCommerce</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="py-3">Pedido</th><th>Cliente</th><th>Status</th><th>Total</th><th>Data</th></tr></thead><tbody>{data?.orders?.length ? data.orders.map(order => <tr key={order.id} className="border-b border-slate-100"><td className="py-3 font-black">#{order.woo_order_id}</td><td><p className="font-bold">{order.customer_name || 'Cliente'}</p><p className="text-xs text-slate-500">{order.customer_email || 'Sem e-mail'}</p></td><td><span className="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-bold text-violet-700">{order.status}</span></td><td className="font-bold">{Number(order.total).toLocaleString('pt-BR', { style: 'currency', currency: order.currency || 'BRL' })}</td><td className="text-slate-500">{order.date_created ? new Date(order.date_created).toLocaleString('pt-BR') : '—'}</td></tr>) : <tr><td colSpan={5} className="py-8 text-center text-slate-500">Nenhum pedido importado ainda.</td></tr>}</tbody></table></div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Histórico recente</h2><button onClick={() => void load()} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Atualizar"><RefreshCw className="h-4 w-4" /></button></div><div className="mt-4 space-y-2">{data?.logs?.length ? data.logs.map(log => <div key={log.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3 text-sm"><div><b>{log.entity_type === 'order' ? 'Pedidos' : log.entity_type === 'connection' ? 'Conexão' : 'Produtos'}</b><p className="text-xs text-slate-500">{log.message}</p></div><div className="text-right"><span className={log.status === 'success' ? 'font-bold text-emerald-600' : 'font-bold text-amber-600'}>{log.processed_count} concluído(s){log.failed_count ? ` · ${log.failed_count} falha(s)` : ''}</span><p className="text-xs text-slate-400">{new Date(log.created_at).toLocaleString('pt-BR')}</p></div></div>) : <p className="py-6 text-center text-sm text-slate-500">Nenhuma sincronização realizada.</p>}</div></section>
      <button onClick={() => void disconnect()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-rose-200 px-4 text-sm font-black text-rose-600 hover:bg-rose-50"><Unplug className="h-4 w-4" />Desconectar WooCommerce</button>
    </>}
  </div>;
}

function SyncCard({ icon,title,description,enabled,busy,onToggle,onRun,actionLabel = 'Sincronizar agora' }: { icon: ReactNode; title: string; description: string; enabled: boolean; busy: boolean; onToggle: (value: boolean) => void; onRun: () => void; actionLabel?: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="rounded-xl bg-violet-50 p-2 text-violet-700">{icon}</div><input type="checkbox" checked={enabled} onChange={e => onToggle(e.target.checked)} className="h-5 w-5 accent-violet-600" aria-label={`Ativar ${title}`} /></div><h3 className="mt-4 font-black text-slate-900">{title}</h3><p className="mt-1 min-h-10 text-sm text-slate-500">{description}</p><button onClick={onRun} disabled={!enabled || busy} className="mt-4 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 text-sm font-black text-white disabled:opacity-40">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}{actionLabel}</button></article>; }

function WooImportPicker({ products,selectedIds,loading,importing,onClose,onChange,onImport }: { products: WooCatalogProduct[]; selectedIds: number[]; loading: boolean; importing: boolean; onClose: () => void; onChange: (ids: number[]) => void; onImport: () => void }) {
  const availableIds = products.filter(product => !product.alreadyImported).map(product => product.id);
  const toggle = (id: number) => onChange(selectedIds.includes(id) ? selectedIds.filter(item => item !== id) : [...selectedIds, id]);
  return <section className="rounded-3xl border-2 border-violet-200 bg-white p-5 shadow-lg sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-black text-slate-950"><PackageCheck className="h-6 w-6 text-violet-600" />Vistoria antes da importação</h2><p className="mt-1 text-sm text-slate-600">Marque somente os produtos que devem entrar na Educalizando. Eles serão salvos como rascunho incompleto.</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Fechar"><X className="h-5 w-5" /></button></div>{loading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-violet-600" /></div> : <><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-slate-700">{selectedIds.length} selecionado(s) de {availableIds.length} disponível(is)</p><div className="flex gap-2"><button onClick={() => onChange(availableIds)} className="rounded-lg border px-3 py-2 text-xs font-black">Marcar todos</button><button onClick={() => onChange([])} className="rounded-lg border px-3 py-2 text-xs font-black">Limpar</button></div></div><div className="mt-4 grid max-h-[32rem] gap-3 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{products.map(product => <label key={product.id} className={`flex cursor-pointer gap-3 rounded-2xl border p-3 ${product.alreadyImported ? 'cursor-default bg-slate-50 opacity-70' : selectedIds.includes(product.id) ? 'border-violet-500 bg-violet-50' : 'border-slate-200'}`}><input type="checkbox" checked={selectedIds.includes(product.id)} disabled={product.alreadyImported} onChange={() => toggle(product.id)} className="mt-1 h-5 w-5 accent-violet-600" />{product.image ? <img src={product.image} alt="" className="h-16 w-16 rounded-lg object-cover" /> : <div className="h-16 w-16 shrink-0 rounded-lg bg-slate-100" />}<span className="min-w-0 text-sm"><b className="line-clamp-2 text-slate-900">{product.name}</b><span className="mt-1 block font-bold text-violet-700">{product.price.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</span><span className="block text-xs text-slate-500">{product.alreadyImported ? 'Já importado' : `Woo: ${product.status}`}</span></span></label>)}</div>{!products.length && <p className="py-10 text-center text-sm text-slate-500">Nenhum produto encontrado no WooCommerce.</p>}<div className="mt-5 flex justify-end"><button onClick={onImport} disabled={!selectedIds.length || importing} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-black text-white disabled:opacity-40">{importing && <Loader2 className="h-4 w-4 animate-spin" />}Importar {selectedIds.length} produto(s)</button></div></>}</section>;
}
