'use client';

import StudentHeader from '@/components/aluno/StudentHeader';
import { Crown,Loader2,RefreshCw } from 'lucide-react';
import Link from 'next/link';
import { useEffect,useState } from 'react';

export default function StudentClubsPage() {
  type ClubSubscription = { id:string; status:string; expires_at:string|null; club:{ id:string; name:string; slug:string; cover_url:string|null; stores:{ nome_loja:string }|Array<{ nome_loja:string }> }|Array<{ id:string; name:string; slug:string; cover_url:string|null; stores:{ nome_loja:string }|Array<{ nome_loja:string }> }> };
  const [items,setItems]=useState<ClubSubscription[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/aluno/clubes',{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);setItems(p.subscriptions||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  return <div className="min-h-screen bg-slate-50"><StudentHeader/><main className="mx-auto max-w-7xl px-4 py-8"><header className="rounded-3xl bg-gradient-to-br from-blue-950 to-violet-700 p-7 text-white"><p className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-blue-200"><Crown className="h-4 w-4"/> Área de assinaturas</p><h1 className="mt-3 text-3xl font-black">Meus Clubes</h1><p className="mt-2 text-sm text-blue-100">Acesse os acervos liberados e acompanhe pagamentos que ainda estão em confirmação.</p></header>{loading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-700"/></div>:error?<p className="mt-6 rounded-2xl bg-rose-50 p-5 font-bold text-rose-700">{error}</p>:items.length===0?<div className="mt-7 rounded-3xl border bg-white p-10 text-center"><Crown className="mx-auto h-12 w-12 text-blue-600"/><h2 className="mt-4 text-xl font-black">Você ainda não assinou um clube</h2><p className="mt-2 text-sm text-slate-500">Depois do pagamento confirmado, o clube aparecerá aqui automaticamente.</p></div>:<div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item)=>{const club=Array.isArray(item.club)?item.club[0]:item.club;const store=Array.isArray(club?.stores)?club.stores[0]:club?.stores;const active=item.status==='active'&&Boolean(item.expires_at)&&new Date(item.expires_at as string)>new Date();return <article key={item.id} className="overflow-hidden rounded-3xl border bg-white shadow-sm">{club?.cover_url?<img src={club.cover_url} alt="" className="aspect-[16/8] w-full object-cover"/>:<div className="flex aspect-[16/8] items-center justify-center bg-blue-50"><Crown className="h-12 w-12 text-blue-600"/></div>}<div className="p-5"><p className="text-xs font-black uppercase tracking-wider text-blue-700">{store?.nome_loja}</p><h2 className="mt-2 text-xl font-black text-slate-950">{club?.name}</h2><div className={`mt-4 rounded-xl p-3 text-sm font-bold ${active?'bg-emerald-50 text-emerald-800':'bg-amber-50 text-amber-800'}`}>{active?`Ativo até ${new Date(item.expires_at as string).toLocaleDateString('pt-BR')}`:item.status==='pending'?'Pagamento em confirmação':'Assinatura expirada'}</div>{active?<Link href={`/cliente/clubes/${club.id}`} className="mt-4 flex min-h-12 items-center justify-center rounded-xl bg-blue-700 font-black text-white">Acessar materiais</Link>:item.status==='pending'?<button onClick={()=>location.reload()} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-amber-300 font-black text-amber-800"><RefreshCw className="h-4 w-4"/>Atualizar confirmação</button>:<Link href={`/clube/${club?.slug}`} className="mt-4 flex min-h-12 items-center justify-center rounded-xl bg-blue-700 font-black text-white">Renovar por 30 dias</Link>}</div></article>})}</div>}</main></div>;
}

