'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, LoaderCircle, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

type Attempt = { id: string; order_id: string; channel: string; event_type: string; status: 'PROCESSING' | 'SENT' | 'FAILED'; last_error?: string | null; last_attempt_at: string; order?: { buyer_email?: string | null } | null };
const label: Record<string, string> = { MATERIAL_DELIVERY: 'Entrega de materiais', PAYMENT_CONFIRMED: 'Pagamento aprovado', CREATOR_SALE_ALERT: 'Alerta de venda' };

export function DeliveryAttemptsPanel() {
  const [items, setItems] = useState<Attempt[]>([]); const [loading, setLoading] = useState(true); const [retrying, setRetrying] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const res = await fetch('/api/admin/delivery-attempts', { cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Não foi possível carregar os envios.'); setItems(data.attempts || []); } catch (error) { toast.error(error instanceof Error ? error.message : 'Erro ao carregar envios.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const retry = async (id: string) => { setRetrying(id); try { const res = await fetch('/api/admin/delivery-attempts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'retry', id }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Não foi possível reenviar.'); toast.success('E-mail de entrega reenviado.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Erro ao reenviar.'); } finally { setRetrying(null); } };
  const failed = items.filter(item => item.status === 'FAILED').length;
  return <section className="rounded-2xl border border-slate-800 bg-slate-950 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-white">Fila de entregas por pedido</h2><p className="mt-1 text-sm text-slate-400">Histórico real. Um envio concluído não é duplicado quando o webhook se repete.</p></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${failed ? 'bg-rose-500/15 text-rose-300' : 'bg-emerald-500/15 text-emerald-300'}`}>{failed ? `${failed} falha(s)` : 'Sem falhas'}</span><button onClick={() => void load()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-700 px-3 text-sm font-bold text-slate-200"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Atualizar</button></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[700px] w-full text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase text-slate-500"><tr><th className="px-3 py-3">Pedido / e-mail</th><th className="px-3 py-3">Evento</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Erro</th><th className="px-3 py-3 text-right">Ação</th></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="px-3 py-8 text-center text-slate-400">Carregando...</td></tr> : items.length === 0 ? <tr><td colSpan={5} className="px-3 py-8 text-center text-slate-400">Nenhum envio registrado ainda.</td></tr> : items.map(item => <tr key={item.id} className="border-b border-slate-900"><td className="px-3 py-3"><p className="font-bold text-white">#{item.order_id.slice(-8).toUpperCase()}</p><p className="text-xs text-slate-400">{item.order?.buyer_email || 'Indisponível'}</p></td><td className="px-3 py-3 text-slate-300">{label[item.event_type] || item.event_type}</td><td className="px-3 py-3">{item.status === 'SENT' ? <span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 className="h-4 w-4" />Enviado</span> : item.status === 'FAILED' ? <span className="inline-flex items-center gap-1 text-rose-300"><AlertTriangle className="h-4 w-4" />Falhou</span> : <span className="text-amber-300">Processando</span>}</td><td className="max-w-xs truncate px-3 py-3 text-xs text-rose-300" title={item.last_error || ''}>{item.last_error || '—'}</td><td className="px-3 py-3 text-right">{item.status === 'FAILED' && item.channel === 'EMAIL' && item.event_type === 'MATERIAL_DELIVERY' ? <button onClick={() => void retry(item.id)} disabled={retrying === item.id} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-violet-600 px-3 text-xs font-black text-white disabled:opacity-50">{retrying === item.id ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}Reenviar</button> : '—'}</td></tr>)}</tbody></table></div></section>;
}
