'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { FilePenLine, Loader2, Send, UserRound } from 'lucide-react';
import { supabase } from '@/lib/supabase';
export default function ClientExclusiveRequestComposer() {
  const params = useSearchParams(); const router = useRouter(); const slug = params.get('solicitar');
  const [store, setStore] = useState<any>(null); const [user, setUser] = useState<any>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!slug) return; Promise.all([supabase.auth.getUser(), fetch(`/api/exclusive-material/store/${encodeURIComponent(slug)}`).then(r => r.json())]).then(([session, data]) => { setUser(session.data.user); if (data.store) setStore(data.store); else setError(data.error || 'Esta loja não recebe solicitações.'); }); }, [slug]);
  if (!slug) return null;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!store) return; const form = new FormData(event.currentTarget); setSaving(true); setError(''); try { const response = await fetch('/api/exclusive-material', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ storeId: store.id, title: form.get('title'), quantity: Number(form.get('quantity')), genre: form.get('genre'), fileType: form.get('fileType'), targetAudience: form.get('targetAudience'), deadline: form.get('deadline'), budget: form.get('budget'), description: form.get('description'), referenceLinks: String(form.get('references') || '').split(/\n|,/).map(value => value.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível criar o pedido.'); router.replace('/cliente/materiais-exclusivos'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Tente novamente.'); } finally { setSaving(false); } }
  return <section className="mb-7 rounded-3xl border border-violet-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-2xl bg-violet-100 p-3 text-violet-700"><FilePenLine className="h-6 w-6"/></div><div><p className="text-xs font-black uppercase tracking-widest text-violet-600">Novo pedido personalizado</p><h2 className="mt-1 text-xl font-black text-slate-950">Solicitar para {store?.nome_loja || 'a loja'}</h2><p className="mt-1 text-sm text-slate-600">O pedido será enviado ao criador para conversa e cotação.</p></div></div></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-slate-50 p-3 text-sm"><UserRound className="h-5 w-5 text-blue-600"/><div><strong className="block text-slate-900">{user?.user_metadata?.full_name || 'Sua conta de cliente'}</strong><span className="text-slate-500">{user?.email || 'Carregando dados da conta...'}</span></div></div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</p>}{store && <form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2"><input name="title" required placeholder="Título do material" className="rounded-xl border px-3 py-3 text-sm sm:col-span-2"/><input name="quantity" required type="number" min="1" defaultValue="1" className="rounded-xl border px-3 py-3 text-sm"/><input name="genre" placeholder="Tema ou gênero" className="rounded-xl border px-3 py-3 text-sm"/><select name="fileType" className="rounded-xl border px-3 py-3 text-sm"><option>PDF para imprimir</option><option>PDF editável</option><option>Imagem</option><option>Apresentação</option><option>Outro</option></select><input name="targetAudience" placeholder="Público ou ano escolar" className="rounded-xl border px-3 py-3 text-sm"/><input name="deadline" type="date" className="rounded-xl border px-3 py-3 text-sm"/><input name="budget" type="number" min="0" step="0.01" placeholder="Orçamento (opcional)" className="rounded-xl border px-3 py-3 text-sm"/><textarea name="description" required minLength={20} rows={4} placeholder="Descreva tudo o que espera receber." className="rounded-xl border px-3 py-3 text-sm sm:col-span-2"/><textarea name="references" rows={2} placeholder="Links de referência, um por linha (opcional)" className="rounded-xl border px-3 py-3 text-sm sm:col-span-2"/><button disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-black text-white disabled:opacity-60 sm:col-span-2">{saving ? <Loader2 className="h-4 w-4 animate-spin"/> : <Send className="h-4 w-4"/>}Enviar para cotação</button></form>}</section>;
}
