'use client';

import { ChangeEvent, useState } from 'react';
import { Download, FileArchive, FileImage, FileText, QrCode, Scissors, Sparkles, Wrench } from 'lucide-react';
import imageCompression from 'browser-image-compression';
import QRCode from 'qrcode';
import JSZip from 'jszip';
import { PDFDocument, degrees } from 'pdf-lib';

const download = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
const pdfBlob = (bytes: Uint8Array) => new Blob([bytes.slice().buffer], { type: 'application/pdf' });

export default function CreatorToolsPage() {
  const [qrText, setQrText] = useState(''); const [qrUrl, setQrUrl] = useState(''); const [coverTitle, setCoverTitle] = useState(''); const [coverColor, setCoverColor] = useState('#155eef'); const [status, setStatus] = useState('');
  const processImage = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setStatus('Processando imagem…'); try { const result = await imageCompression(file, { maxSizeMB: 1, maxWidthOrHeight: 2000, useWebWorker: true, fileType: 'image/webp' }); download(result, `${file.name.replace(/\.[^.]+$/, '')}.webp`); setStatus('Imagem otimizada e convertida para WebP.'); } catch { setStatus('Não foi possível processar esta imagem.'); } };
  const processPdf = async (event: ChangeEvent<HTMLInputElement>, mode: 'merge' | 'split' | 'rotate') => { const files = Array.from(event.target.files || []); if (!files.length) return; setStatus('Processando PDF…'); try { if (mode === 'merge') { const out = await PDFDocument.create(); for (const file of files) { const doc = await PDFDocument.load(await file.arrayBuffer()); const pages = await out.copyPages(doc, doc.getPageIndices()); pages.forEach((page) => out.addPage(page)); } download(pdfBlob(await out.save()), 'pdf-unido.pdf'); } else { const doc = await PDFDocument.load(await files[0].arrayBuffer()); if (mode === 'rotate') doc.getPages().forEach((page) => page.setRotation(degrees(page.getRotation().angle + 90))); if (mode === 'split') { for (let index = 0; index < doc.getPageCount(); index++) { const out = await PDFDocument.create(); const [page] = await out.copyPages(doc, [index]); out.addPage(page); download(pdfBlob(await out.save()), `pagina-${index + 1}.pdf`); } } else download(pdfBlob(await doc.save()), 'pdf-girado.pdf'); } setStatus('PDF pronto para baixar.'); } catch { setStatus('Não foi possível processar o PDF.'); } };
  const zipFiles = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); if (!files.length) return; const zip = new JSZip(); files.forEach((file) => zip.file(file.name, file)); download(await zip.generateAsync({ type: 'blob' }), 'materiais-educalizando.zip'); setStatus('Arquivo ZIP criado.'); };
  const makeQr = async () => { if (!qrText.trim()) return; setQrUrl(await QRCode.toDataURL(qrText, { width: 600, margin: 2 })); };
  const makeCover = () => { const canvas = document.createElement('canvas'); canvas.width = canvas.height = 1080; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.fillStyle = coverColor; ctx.fillRect(0, 0, 1080, 1080); ctx.fillStyle = '#ffffff'; ctx.font = 'bold 84px Arial'; ctx.textAlign = 'center'; const words = (coverTitle || 'Seu Material').split(' '); const lines: string[] = []; let line = ''; words.forEach((word) => { if ((line + word).length > 17) { lines.push(line); line = `${word} `; } else line += `${word} `; }); lines.push(line); lines.forEach((value, index) => ctx.fillText(value.trim(), 540, 470 + index * 100)); ctx.font = 'bold 36px Arial'; ctx.fillText('Educalizando', 540, 970); canvas.toBlob((blob) => blob && download(blob, 'capa-educalizando-1080x1080.png'), 'image/png'); };
  const tools = [
    { title: 'Imagens', icon: FileImage, description: 'Comprimir, redimensionar e converter para WebP.', input: <input type="file" accept="image/*,.heic" onChange={processImage} /> },
    { title: 'Unir PDFs', icon: FileText, description: 'Junte vários PDFs em um só arquivo.', input: <input type="file" accept="application/pdf" multiple onChange={(e) => processPdf(e, 'merge')} /> },
    { title: 'Dividir ou girar PDF', icon: Scissors, description: 'Baixe cada página separadamente ou gire 90°.', input: <div className="flex gap-2"><input type="file" accept="application/pdf" onChange={(e) => processPdf(e, 'split')} /><input type="file" accept="application/pdf" onChange={(e) => processPdf(e, 'rotate')} /></div> },
    { title: 'Criar ZIP', icon: FileArchive, description: 'Compacte vários materiais em um arquivo ZIP.', input: <input type="file" multiple onChange={zipFiles} /> },
  ];
  return <div className="space-y-6"><section className="rounded-3xl bg-gradient-to-br from-brand-navy to-blue-600 p-6 text-white sm:p-8"><div className="flex items-center gap-3"><Wrench className="h-8 w-8 text-amber-300" /><div><h1 className="text-2xl font-black">Caixa de Ferramentas</h1><p className="mt-1 text-sm text-blue-100">Crie e organize seus materiais. Seus arquivos ficam somente no seu dispositivo.</p></div></div></section>{status && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{status}</p>}<section className="grid gap-4 md:grid-cols-2">{tools.map(({ title, icon: Icon, description, input }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Icon className="h-6 w-6 text-brand-navy" /><h2 className="mt-3 font-black text-slate-900">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p><div className="mt-4 text-xs">{input}</div></article>)}</section><section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><QrCode className="h-6 w-6 text-brand-navy" /><h2 className="font-black">Gerar QR Code</h2></div><input value={qrText} onChange={(e) => setQrText(e.target.value)} placeholder="Link, texto ou WhatsApp" className="mt-4 w-full rounded-xl border p-3 text-sm" /><button onClick={makeQr} className="mt-3 rounded-xl bg-brand-navy px-4 py-2 text-xs font-bold text-white">Gerar QR Code</button>{qrUrl && <div className="mt-4"><img src={qrUrl} alt="QR Code" className="h-44 w-44" /><a href={qrUrl} download="qrcode-educalizando.png" className="mt-2 inline-flex gap-1 text-xs font-bold text-blue-700"><Download className="h-4 w-4" /> Baixar</a></div>}</article><article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><Sparkles className="h-6 w-6 text-brand-navy" /><h2 className="font-black">Capa 1:1 para produto</h2></div><input value={coverTitle} onChange={(e) => setCoverTitle(e.target.value)} placeholder="Título do material" className="mt-4 w-full rounded-xl border p-3 text-sm" /><input type="color" value={coverColor} onChange={(e) => setCoverColor(e.target.value)} className="mt-3 h-10 w-full" /><button onClick={makeCover} className="mt-3 rounded-xl bg-brand-navy px-4 py-2 text-xs font-bold text-white">Criar capa 1080 × 1080</button></article></section></div>;
}
