'use client';

import { FormEvent, useState } from 'react';
import { Loader2, Mail, CheckCircle2 } from 'lucide-react';

export default function NewsletterForm() {
  const [email, setEmail] = useState(''); const [state, setState] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [message, setMessage] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setState('loading'); try { const response = await fetch('/api/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, source: 'rodape' }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setState('success'); setMessage('Pronto! Você receberá nossas novidades.'); setEmail(''); } catch (error: any) { setState('error'); setMessage(error.message || 'Tente novamente em instantes.'); } };
  return <div className="rounded-2xl border border-blue-100 bg-blue-50 p-5"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-600 text-white"><Mail className="h-5 w-5" /></div><div><h3 className="font-black text-slate-900">Receba materiais e ideias</h3><p className="mt-1 text-xs leading-relaxed text-slate-600">Novidades pedagógicas e materiais gratuitos no seu e-mail.</p></div></div><form onSubmit={submit} className="mt-4 flex gap-2"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Seu melhor e-mail" className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none focus:border-blue-500" /><button disabled={state === 'loading'} className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-xl bg-blue-600 px-3 text-sm font-bold text-white disabled:opacity-60">{state === 'loading' ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Quero receber'}</button></form>{state !== 'idle' && <p className={`mt-3 flex items-center gap-1.5 text-xs font-bold ${state === 'success' ? 'text-emerald-700' : 'text-rose-700'}`}>{state === 'success' && <CheckCircle2 className="h-4 w-4" />}{message}</p>}<p className="mt-3 text-[10px] leading-relaxed text-slate-500">Ao se inscrever, você concorda em receber comunicações da Educalizando. Você pode cancelar quando quiser.</p></div>;
}
