'use client';

import { useEffect, useMemo, useState } from 'react';
import { Eye, EyeOff, Loader2, MessageSquare, Search, Star } from 'lucide-react';
import { toast } from 'sonner';

type Review = { id: string; nota: number; comentario?: string | null; status: 'aprovado' | 'oculto'; created_at: string; products?: { titulo?: string } | null; stores?: { nome_loja?: string } | null };
export default function AdminReviewsPage() {
  const [reviews, setReviews] = useState<Review[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState('');
  const load = async () => { try { const response = await fetch('/api/admin/reviews'); const body = await response.json(); if (!response.ok) throw new Error(body.error); setReviews(body.reviews || []); } catch (error: any) { toast.error(error.message || 'Não foi possível carregar avaliações.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => reviews.filter((review) => `${review.products?.titulo || ''} ${review.stores?.nome_loja || ''} ${review.comentario || ''}`.toLowerCase().includes(query.toLowerCase())), [reviews, query]);
  const changeStatus = async (review: Review) => { const status = review.status === 'aprovado' ? 'oculto' : 'aprovado'; try { const response = await fetch('/api/admin/reviews', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: review.id, status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setReviews((current) => current.map((item) => item.id === review.id ? { ...item, status } : item)); toast.success(status === 'oculto' ? 'Avaliação ocultada da vitrine.' : 'Avaliação restaurada na vitrine.'); } catch (error: any) { toast.error(error.message || 'Não foi possível alterar a avaliação.'); } };
  return <div className="space-y-6"><div className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h1 className="flex items-center gap-2 text-2xl font-bold"><MessageSquare className="text-blue-500" /> Avaliações de clientes</h1><p className="mt-1 text-sm text-slate-400">Modere avaliações verificadas sem apagar o registro do comprador.</p></div><div className="rounded-xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-4"><label className="flex min-h-11 items-center gap-2 rounded-lg border border-slate-700 bg-slate-950 px-3"><Search className="h-4 w-4 text-slate-500" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar material, loja ou comentário" className="min-w-0 flex-1 bg-transparent text-sm text-slate-100 outline-none" /></label></div>{loading ? <div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin text-blue-500" /></div> : <div className="divide-y divide-slate-800">{filtered.length ? filtered.map((review) => <article key={review.id} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold text-slate-100">{review.products?.titulo || 'Material removido'}</p><p className="mt-1 text-xs text-slate-500">{review.stores?.nome_loja || 'Loja'} · {new Date(review.created_at).toLocaleDateString('pt-BR')}</p><div className="mt-2 flex text-amber-400">{Array.from({ length: 5 }).map((_, index) => <Star key={index} className={`h-4 w-4 ${index < review.nota ? 'fill-current' : 'text-slate-700'}`} />)}</div></div><button onClick={() => changeStatus(review)} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-xs font-bold ${review.status === 'aprovado' ? 'bg-rose-500/10 text-rose-300 hover:bg-rose-500/20' : 'bg-emerald-500/10 text-emerald-300 hover:bg-emerald-500/20'}`}>{review.status === 'aprovado' ? <><EyeOff className="h-4 w-4" /> Ocultar</> : <><Eye className="h-4 w-4" /> Restaurar</>}</button></div>{review.comentario && <p className="mt-4 text-sm leading-relaxed text-slate-300">“{review.comentario}”</p>}<p className={`mt-3 text-[10px] font-black uppercase tracking-wider ${review.status === 'aprovado' ? 'text-emerald-400' : 'text-amber-400'}`}>{review.status}</p></article>) : <p className="p-10 text-center text-sm text-slate-500">Nenhuma avaliação encontrada.</p>}</div>}</div></div>;
}
