import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, BookOpen, ChevronRight, CheckCircle2 } from 'lucide-react';
import MarketplaceHeader from '@/components/MarketplaceHeader';
import Footer from '@/components/Footer';
import { getGlossaryTerm, glossaryTerms } from '@/lib/glossary';
import { notFound } from 'next/navigation';

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return glossaryTerms.map((term) => ({ slug: term.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const term = getGlossaryTerm((await params).slug); return term ? { title: `${term.title} | Glossário Pedagógico Educalizando`, description: term.summary } : {}; }
export default async function GlossaryTermPage({ params }: Props) { const term = getGlossaryTerm((await params).slug); if (!term) notFound(); const related = term.related.map(getGlossaryTerm).filter(Boolean); const url = `https://www.educalizando.com.br/glossario/${term.slug}`; return <div className="flex min-h-screen flex-col bg-slate-50"><MarketplaceHeader /><main className="flex-1"><article className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-14"><Link href="/glossario" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-blue-700 hover:text-blue-900"><ArrowLeft className="h-4 w-4" />Voltar ao glossário</Link><p className="mt-8 text-xs font-black uppercase tracking-[.18em] text-teal-600">Glossário Pedagógico Educalizando</p><h1 className="mt-3 text-3xl font-black leading-tight text-slate-900 sm:text-5xl">{term.title}</h1><p className="mt-4 text-lg leading-relaxed text-slate-600">{term.summary}</p><section className="mt-9 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-2 text-blue-700"><BookOpen className="h-5 w-5" /><h2 className="text-xl font-black">Definição</h2></div><p className="mt-4 leading-8 text-slate-700">{term.definition}</p></section><section className="mt-8"><h2 className="text-2xl font-black text-slate-900">Exemplos práticos</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{term.examples.map((example) => <p key={example} className="rounded-2xl border border-teal-100 bg-teal-50 p-4 text-sm leading-relaxed text-slate-700"><CheckCircle2 className="mb-2 h-5 w-5 text-teal-600" />{example}</p>)}</div></section><section className="mt-8"><h2 className="text-2xl font-black text-slate-900">Perguntas frequentes</h2><div className="mt-4 space-y-3">{term.faq.map((item) => <details key={item.question} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer font-black text-slate-900">{item.question}</summary><p className="mt-3 leading-relaxed text-slate-600">{item.answer}</p></details>)}</div></section>{related.length > 0 && <section className="mt-9 border-t border-slate-200 pt-8"><h2 className="text-xl font-black text-slate-900">Outros termos do glossário</h2><div className="mt-4 flex flex-wrap gap-3">{related.map((item) => item && <Link key={item.slug} href={`/glossario/${item.slug}`} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-blue-100 bg-white px-4 text-sm font-bold text-blue-700 hover:bg-blue-50">{item.title}<ChevronRight className="h-4 w-4" /></Link>)}</div></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'DefinedTerm', name: term.title, description: term.definition, url, inDefinedTermSet: 'https://www.educalizando.com.br/glossario' }) }} /></article></main><Footer /></div>; }
