'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpen, CalendarDays, CircleDollarSign, Copy, Gift, Link2, RefreshCw, Send, Share2, Sparkles, TrendingUp, Users, Wallet } from 'lucide-react';

type Referral = { id: string; creatorName: string; storeName: string; attributedAt: string; eligibleUntil: string; status: string; ratePercent: number; eligibleSalesAmount: number; eligibleSalesCount: number; commissionAvailable: number; commissionReversed: number; commissionGenerated: number };
type ReferralData = { code: string; referrals: Referral[]; totals: { eligibleSalesAmount: number; eligibleSalesCount: number; commissionAvailable: number; commissionReversed: number; commissionGenerated: number } };

const money = (amount: number) => amount.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const date = (value: string) => new Date(value).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' });
const daysLeft = (value: string) => Math.max(0, Math.ceil((new Date(value).getTime() - Date.now()) / 86_400_000));

export default function CreatorReferralsPage() {
  const [data, setData] = useState<ReferralData | null>(null);
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => {
    setLoading(true); setError('');
    try { const response = await fetch('/api/creator-referrals', { cache: 'no-store' }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); } catch { setError('Não foi possível carregar suas indicações agora.'); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  const link = useMemo(() => data ? `${typeof window === 'undefined' ? '' : window.location.origin}/cadastro/produtor?ref=${data.code}` : '', [data]);
  const copy = async () => { await navigator.clipboard.writeText(link); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  const shareWhatsApp = () => window.open(`https://wa.me/?text=${encodeURIComponent(`Crie sua loja grátis na Educalizando pelo meu link e comece a vender materiais: ${link}`)}`, '_blank', 'noopener,noreferrer');
  const totals = data?.totals;

  return <div className="space-y-6 pb-8">
    <section className="relative isolate overflow-hidden rounded-[2rem] border border-sky-100 bg-[#f7fbff] px-6 py-7 shadow-[0_22px_55px_-35px_rgba(3,105,161,.55)] sm:px-9 sm:py-10">
      <div className="pointer-events-none absolute -left-20 top-0 h-64 w-64 rounded-full bg-cyan-200/55 blur-3xl animate-pulse" /><div className="pointer-events-none absolute -right-24 bottom-0 h-72 w-72 rounded-full bg-lime-200/55 blur-3xl animate-pulse [animation-delay:900ms]" /><div className="pointer-events-none absolute right-[38%] top-0 h-full w-px bg-sky-200/70" /><span className="pointer-events-none absolute right-[8%] top-[18%] h-3 w-3 rounded-full bg-lime-400 shadow-[0_0_0_8px_rgba(163,230,53,.18)] animate-ping" /><span className="pointer-events-none absolute bottom-[19%] left-[44%] h-2.5 w-2.5 rounded-full bg-sky-500 shadow-[0_0_0_7px_rgba(14,165,233,.12)] animate-pulse" />
      <div className="relative grid items-center gap-8 lg:grid-cols-[1.08fr_.92fr]">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-white/80 px-3 py-1.5 text-xs font-black text-sky-800 shadow-sm"><Sparkles className="h-4 w-4 text-cyan-600" /> Comunidade que cresce junto</span><h1 className="mt-5 max-w-xl text-3xl font-black tracking-[-0.045em] text-slate-950 sm:text-5xl sm:leading-[1.02]">Indique quem ensina.<br /><span className="text-sky-600">Veja seu impacto crescer.</span></h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-600 sm:text-base">Seu link abre espaço para novas criadoras e mantém tudo visível: quem chegou, o que vendeu e qual bônus já entrou na sua carteira.</p><div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-3 text-sm font-bold text-slate-700"><span className="inline-flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-sky-600 text-white"><Send className="h-3.5 w-3.5" /></span> Indicações ilimitadas</span><span className="inline-flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-500 text-white"><CircleDollarSign className="h-3.5 w-3.5" /></span> 3% por venda paga</span></div></div>
        <div className="relative rounded-3xl border border-white/80 bg-white/75 p-5 shadow-xl shadow-sky-900/10 backdrop-blur sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-sky-700">Seu círculo de impacto</p><p className="mt-1 text-sm font-semibold text-slate-500">Acompanhe a jornada em tempo real</p></div><div className="rounded-2xl bg-sky-100 p-3 text-sky-700"><BookOpen className="h-6 w-6" /></div></div><div className="relative mt-7 grid grid-cols-3 gap-2 before:absolute before:left-[16%] before:right-[16%] before:top-5 before:h-0.5 before:bg-gradient-to-r before:from-sky-300 before:via-emerald-300 before:to-lime-300"><Journey icon={Share2} number="01" title="Você compartilha" color="bg-sky-600" /><Journey icon={Users} number="02" title="Ela cria a conta" color="bg-emerald-500" /><Journey icon={Wallet} number="03" title="Bônus na carteira" color="bg-lime-500" /></div><div className="mt-6 flex items-center justify-between rounded-2xl bg-slate-950 px-4 py-3 text-white"><div><p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Criadoras no seu círculo</p><p className="mt-0.5 text-xl font-black">{data ? data.referrals.length : '—'} <span className="text-sm font-semibold text-slate-300">indicada{data?.referrals.length === 1 ? '' : 's'}</span></p></div><ArrowRight className="h-5 w-5 text-lime-300" /></div></div>
      </div>
    </section>

    {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800"><p className="font-black">Não foi possível atualizar este painel.</p><p className="mt-1">{error}</p><button onClick={() => void load()} className="mt-3 rounded-lg bg-rose-700 px-3 py-2 text-xs font-bold text-white">Tentar novamente</button></div> : <>
      <section className="rounded-2xl border border-violet-200 bg-violet-50/80 p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Link2 className="h-5 w-5 text-violet-700" /><h2 className="font-black text-slate-950">Seu link de indicação</h2></div><p className="mt-1 text-sm text-slate-600">Cada criadora indicada fica vinculada a você por 12 meses.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-bold text-violet-700 hover:bg-violet-100 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Atualizar</button></div><div className="mt-4 flex flex-col gap-3 lg:flex-row"><code className="min-w-0 flex-1 truncate rounded-xl border border-violet-200 bg-white px-4 py-3 text-sm text-slate-800">{data ? link : 'Gerando seu link...'}</code><button onClick={copy} disabled={!data} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold"><Copy className="h-4 w-4" />{copied ? 'Copiado!' : 'Copiar'}</button><button onClick={shareWhatsApp} disabled={!data} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-lime-400 px-4 text-sm font-black text-slate-950"><Share2 className="h-4 w-4" />WhatsApp</button></div></section>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Criadoras indicadas" value={data ? String(data.referrals.length) : '—'} detail="Contas vinculadas ao seu link" tone="violet" /><Metric icon={TrendingUp} label="Vendas elegíveis" value={totals ? money(totals.eligibleSalesAmount) : '—'} detail={`${totals?.eligibleSalesCount ?? 0} vendas confirmadas`} tone="blue" /><Metric icon={Wallet} label="Bônus disponível" value={totals ? money(totals.commissionAvailable) : '—'} detail="Já creditado na sua carteira" tone="emerald" /><Metric icon={CircleDollarSign} label="Bônus gerado" value={totals ? money(totals.commissionGenerated) : '—'} detail={`${totals ? money(totals.commissionReversed) : money(0)} estornado`} tone="amber" /></section>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-slate-950">Criadoras que você indicou</h2><p className="mt-1 text-sm text-slate-600">Valores por criadora, sem comissão em cascata.</p></div><span className="w-fit rounded-full bg-violet-100 px-3 py-1 text-xs font-black text-violet-800">3% por 12 meses</span></div>{loading && !data ? <div className="p-10 text-center text-sm text-slate-500">Carregando suas indicações...</div> : data?.referrals.length ? <div className="divide-y divide-slate-100">{data.referrals.map(referral => <ReferralRow key={referral.id} referral={referral} />)}</div> : <div className="p-10 text-center"><Users className="mx-auto h-10 w-10 text-violet-200" /><h3 className="mt-3 font-black text-slate-900">Nenhuma criadora indicada ainda</h3><p className="mx-auto mt-1 max-w-md text-sm leading-6 text-slate-500">Compartilhe seu link para acompanhar aqui cada novo cadastro e os bônus das vendas confirmadas.</p></div>}</section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black text-slate-950">Como os valores são calculados</h2><div className="mt-5 grid gap-5 md:grid-cols-3"><Info title="Sem limite de indicações" text="Você pode enviar seu link para quantas criadoras quiser. Cada conta fica ligada somente a quem compartilhou o link." /><Info title="Venda elegível" text="Mostramos somente vendas pagas da criadora indicada dentro do prazo de 12 meses." /><Info title="Bônus e estorno" text="Você recebe 3% da venda na carteira. Se a venda for reembolsada, o bônus correspondente aparece como estornado." /></div><div className="mt-5 flex items-start gap-3 rounded-xl bg-violet-50 p-4 text-sm leading-6 text-violet-950"><CalendarDays className="mt-0.5 h-5 w-5 shrink-0 text-violet-700" /><p><strong>Importante:</strong> o bônus sai da taxa da plataforma. A criadora indicada mantém o valor líquido dela e indicadas de indicadas não geram comissão para você.</p></div></section>
    </>}
  </div>;
}

function Metric({ icon: Icon, label, value, detail, tone }: { icon: typeof Users; label: string; value: string; detail: string; tone: 'violet' | 'blue' | 'emerald' | 'amber' }) {
  const styles = { violet: 'bg-violet-50 text-violet-700', blue: 'bg-blue-50 text-blue-700', emerald: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700' }[tone];
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`inline-flex rounded-xl p-2.5 ${styles}`}><Icon className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs font-medium text-slate-400">{detail}</p></article>;
}

function Journey({ icon: Icon, number, title, color }: { icon: typeof Users; number: string; title: string; color: string }) {
  return <div className="relative z-10 text-center"><span className={`mx-auto flex h-10 w-10 items-center justify-center rounded-2xl text-white shadow-lg ${color}`}><Icon className="h-4 w-4" /></span><p className="mt-2 text-[10px] font-black tracking-wider text-slate-400">{number}</p><p className="mt-0.5 text-xs font-black leading-4 text-slate-800">{title}</p></div>;
}

function ReferralRow({ referral }: { referral: Referral }) {
  const remaining = daysLeft(referral.eligibleUntil); const active = referral.status === 'active' && remaining > 0;
  return <article className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-violet-100 text-sm font-black text-violet-700">{referral.creatorName.charAt(0).toUpperCase()}</div><div className="min-w-0"><h3 className="truncate font-black text-slate-950">{referral.creatorName}</h3><p className="truncate text-sm text-slate-500">Loja: {referral.storeName} · Indicada em {date(referral.attributedAt)}</p></div></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{active ? `${remaining} dias restantes` : 'Prazo encerrado'}</span><span className="rounded-full bg-violet-50 px-2.5 py-1 text-xs font-black text-violet-700">{referral.ratePercent}% de bônus</span></div></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-slate-100 pt-4 sm:grid-cols-4"><SmallValue label="Vendas elegíveis" value={money(referral.eligibleSalesAmount)} detail={`${referral.eligibleSalesCount} confirmada${referral.eligibleSalesCount === 1 ? '' : 's'}`} /><SmallValue label="Bônus disponível" value={money(referral.commissionAvailable)} detail="na carteira" emphasis /><SmallValue label="Bônus gerado" value={money(referral.commissionGenerated)} detail="desde o vínculo" /><SmallValue label="Estornado" value={money(referral.commissionReversed)} detail="vendas reembolsadas" /></div></article>;
}

function SmallValue({ label, value, detail, emphasis = false }: { label: string; value: string; detail: string; emphasis?: boolean }) { return <div><p className="text-xs font-semibold text-slate-500">{label}</p><p className={`mt-1 text-base font-black ${emphasis ? 'text-emerald-700' : 'text-slate-900'}`}>{value}</p><p className="mt-0.5 text-[11px] text-slate-400">{detail}</p></div>; }
function Info({ title, text }: { title: string; text: string }) { return <article><h3 className="font-black text-violet-800">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
