import type { Metadata } from 'next';
import Link from 'next/link';
import { BookOpen, ChevronRight, Search } from 'lucide-react';
import MarketplaceHeader from '@/components/MarketplaceHeader';
import Footer from '@/components/Footer';
import { glossaryTerms } from '@/lib/glossary';

export const metadata: Metadata = { title: 'Glossário Pedagógico | Educalizando', description: 'Entenda termos essenciais da educação, da BNCC e dos materiais pedagógicos digitais.' };

export default function GlossarioPage() {
  const letters = [...new Set(glossaryTerms.map((term) => term.title[0].toUpperCase()))].sort();
  return <div className="flex min-h-screen flex-col bg-slate-50"><MarketplaceHeader /><main className="flex-1"><section className="border-b border-blue-100 bg-gradient-to-br from-blue-50 via-white to-teal-50"><div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Conhecimento para educadores</p><h1 className="mt-3 flex items-center gap-3 text-3xl font-black text-slate-900 sm:text-5xl"><BookOpen className="h-9 w-9 text-teal-500 sm:h-11 sm:w-11" />Glossário Pedagógico</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-slate-600 sm:text-lg">Termos explicados de forma simples para apoiar seu planejamento, a escolha de materiais e a rotina em sala de aula.</p><div className="mt-7 flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-500 shadow-sm"><Search className="h-5 w-5 text-blue-600" /><span>Escolha um termo abaixo para ver definição, exemplos e perguntas frequentes.</span></div></div></section><section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-14"><div className="flex flex-wrap gap-2">{letters.map((letter) => <a key={letter} href={`#letra-${letter}`} className="flex h-10 w-10 items-center justify-center rounded-xl border border-blue-100 bg-white text-sm font-black text-blue-700 transition hover:bg-blue-600 hover:text-white">{letter}</a>)}</div><div className="mt-10 space-y-10">{letters.map((letter) => <section id={`letra-${letter}`} key={letter}><h2 className="border-b border-slate-200 pb-3 text-2xl font-black text-slate-900">{letter}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{glossaryTerms.filter((term) => term.title.startsWith(letter)).map((term) => <Link key={term.slug} href={`/glossario/${term.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><h3 className="flex items-start justify-between gap-3 font-black text-slate-900">{term.title}<ChevronRight className="mt-0.5 h-4 w-4 shrink-0 text-blue-600 transition group-hover:translate-x-1" /></h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{term.summary}</p></Link>)}</div></section>)}</div></section></main><Footer /></div>;
}
